-- ════════════════════════════════════════════════════════════════
-- 06b_schema_his_light_extras.sql
-- Auto-generated: ALTER TABLE ADD COLUMN cho mọi cột PRODUCT_HIS bị
-- thiếu trong clone BenhNhan/TiepNhan/DichVuYeuCau, được scan từ các
-- file SP đã port (07_..14_*.sql).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── DichVuYeuCau: thêm 60 cột HIS ───────────────────────
IF COL_LENGTH('dbo.DichVuYeuCau', 'BACSIBENNGOAI_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD BACSIBENNGOAI_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'BARCODEID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD BARCODEID VARCHAR(50) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'BENHAN_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD BENHAN_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'BENHVIEN_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD BENHVIEN_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'BHYTDONGTIEN') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD BHYTDONGTIEN INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'BNKHONGDENBV') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD BNKHONGDENBV CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'CLOTEST') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD CLOTEST CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'CREATININEMAU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD CREATININEMAU DECIMAL(10,3) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DAITHE') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DAITHE NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DANGKY_CHITIET_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DANGKY_CHITIET_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DANGKY_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DANGKY_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DICHVU_KHAMBENH_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DICHVU_KHAMBENH_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DONVIBENNGOAI_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DONVIBENNGOAI_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DUOCPHEPTHUCHIEN') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DUOCPHEPTHUCHIEN CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DVKEMTHEO') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DVKEMTHEO NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'DVKEMTHEO_KHACEKIP') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD DVKEMTHEO_KHACEKIP NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'GHICHU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD GHICHU NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'GIOYEUCAU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD GIOYEUCAU INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'HINHTHUCTHANHTOAN_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD HINHTHUCTHANHTOAN_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'HOPDONG_BENHNHAN_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD HOPDONG_BENHNHAN_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'HOPDONG_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD HOPDONG_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KETQUAXNKHAC') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KETQUAXNKHAC NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KHAMBENH_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KHAMBENH_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KHAMBENH_NGOAITRU_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KHAMBENH_NGOAITRU_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KHAN') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KHAN CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KHOABENNGOAI') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KHOABENNGOAI NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KHOABENNGOAI_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KHOABENNGOAI_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'KHOADULIEU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD KHOADULIEU CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'LICHHEN_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD LICHHEN_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'LIENCHUYENKHOA') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD LIENCHUYENKHOA NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'LOAIKHACHHANG_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD LOAIKHACHHANG_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'LUUTRU_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD LUUTRU_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'LYDOHUY') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD LYDOHUY NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'MANGUOIKHOA') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD MANGUOIKHOA VARCHAR(50) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'MANGUOINHAPBENHPHAM') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD MANGUOINHAPBENHPHAM VARCHAR(50) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NGAYHENCLS') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NGAYHENCLS DATETIME NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NGAYKHOADULIEU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NGAYKHOADULIEU DATETIME NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NGAYTAO') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NGAYTAO DATETIME NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NGUOIKHOA_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NGUOIKHOA_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NGUOINHANBENHPHAM_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NGUOINHANBENHPHAM_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NGUOITAO_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NGUOITAO_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'NOITHUCHIENTHAYDOI_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD NOITHUCHIENTHAYDOI_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'SINHTHIET') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD SINHTHIET CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'SODICHVUDONGTIEN') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD SODICHVUDONGTIEN INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'TENBACSIBENNGOAI') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD TENBACSIBENNGOAI NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'TENNGUOIKHOA') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD TENNGUOIKHOA NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'TENNGUOINHAPBENHPHAM') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD TENNGUOINHAPBENHPHAM NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THANHTOANTRUOC') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THANHTOANTRUOC CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THE_ID') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THE_ID INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THOIGIANKHOADULIEU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THOIGIANKHOADULIEU DATETIME NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THOIGIANLICHHEN') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THOIGIANLICHHEN DATETIME NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THOIGIANNHANBENHPHAM') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THOIGIANNHANBENHPHAM DATETIME NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THUCHIENBENNGOAI') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THUCHIENBENNGOAI CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THUTIENSAU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THUTIENSAU INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'THUTUYEUCAU') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD THUTUYEUCAU INT NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'TIEMCANQUANG') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD TIEMCANQUANG CHAR(1) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'TRANGTHAI_WFL') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD TRANGTHAI_WFL VARCHAR(50) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'VITHE') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD VITHE NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'VUNGCANKHAOSAT') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD VUNGCANKHAOSAT NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DichVuYeuCau', 'YEUCAUBENNGOAI') IS NULL ALTER TABLE dbo.DichVuYeuCau ADD YEUCAUBENNGOAI CHAR(1) NULL;
GO

-- ─── TiepNhan: thêm 43 cột HIS ───────────────────────
IF COL_LENGTH('dbo.TiepNhan', 'BAOLANH_VIENPHI') IS NULL ALTER TABLE dbo.TiepNhan ADD BAOLANH_VIENPHI NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'BENHVIEN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD BENHVIEN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'BHYTTREN3NAM') IS NULL ALTER TABLE dbo.TiepNhan ADD BHYTTREN3NAM CHAR(1) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'CHANDOANNGT') IS NULL ALTER TABLE dbo.TiepNhan ADD CHANDOANNGT NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'CONGTY_CHITRA_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD CONGTY_CHITRA_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'DIACHILIENHE') IS NULL ALTER TABLE dbo.TiepNhan ADD DIACHILIENHE NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'DONVICONGTAC') IS NULL ALTER TABLE dbo.TiepNhan ADD DONVICONGTAC NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'DONVICONGTAC_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD DONVICONGTAC_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'GIOITHIEUBENNGOAI') IS NULL ALTER TABLE dbo.TiepNhan ADD GIOITHIEUBENNGOAI DATETIME NULL;
IF COL_LENGTH('dbo.TiepNhan', 'HINHTHUCCHUYENVIEN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD HINHTHUCCHUYENVIEN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'ICDNOIGIOITHIEU_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD ICDNOIGIOITHIEU_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'ISTHONGTUYEN') IS NULL ALTER TABLE dbo.TiepNhan ADD ISTHONGTUYEN NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'KHOADULIEU') IS NULL ALTER TABLE dbo.TiepNhan ADD KHOADULIEU CHAR(1) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'KHOAHENTK') IS NULL ALTER TABLE dbo.TiepNhan ADD KHOAHENTK NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'KHUVUCSONG_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD KHUVUCSONG_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'LOAITHANHVIEN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD LOAITHANHVIEN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'LYDOCHUYENVIEN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD LYDOCHUYENVIEN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'LYDOTIEPNHAN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD LYDOTIEPNHAN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NGAYBHYT2') IS NULL ALTER TABLE dbo.TiepNhan ADD NGAYBHYT2 DATETIME NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NGAYKHOA') IS NULL ALTER TABLE dbo.TiepNhan ADD NGAYKHOA DATETIME NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NGOAIGIO') IS NULL ALTER TABLE dbo.TiepNhan ADD NGOAIGIO NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NGUOIGIOITHIEU_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD NGUOIGIOITHIEU_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NGUOINUOCNGOAI') IS NULL ALTER TABLE dbo.TiepNhan ADD NGUOINUOCNGOAI NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NGUON_BENHNHAN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD NGUON_BENHNHAN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'NOIGIOITHIEU_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD NOIGIOITHIEU_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'PROCESS_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD PROCESS_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'QUANHAM_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD QUANHAM_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'QUANHUYEN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD QUANHUYEN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'SOCHUYENVIEN') IS NULL ALTER TABLE dbo.TiepNhan ADD SOCHUYENVIEN NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'SUDUNG_BHTN') IS NULL ALTER TABLE dbo.TiepNhan ADD SUDUNG_BHTN NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'TENNGUOIGIOITHIEU') IS NULL ALTER TABLE dbo.TiepNhan ADD TENNGUOIGIOITHIEU NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'THANHVIEN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD THANHVIEN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'THE_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD THE_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'THOIGIANCHUYENTUYEN') IS NULL ALTER TABLE dbo.TiepNhan ADD THOIGIANCHUYENTUYEN DATETIME NULL;
IF COL_LENGTH('dbo.TiepNhan', 'THONGTIN_KCB_BHYT') IS NULL ALTER TABLE dbo.TiepNhan ADD THONGTIN_KCB_BHYT NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'THUTIENTRUOC') IS NULL ALTER TABLE dbo.TiepNhan ADD THUTIENTRUOC DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'TINHTHANH_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD TINHTHANH_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'TINHTRANGBENHNHAN_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD TINHTRANGBENHNHAN_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'TINHTRANGHEN') IS NULL ALTER TABLE dbo.TiepNhan ADD TINHTRANGHEN NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'TRAITUYEN') IS NULL ALTER TABLE dbo.TiepNhan ADD TRAITUYEN CHAR(1) NULL;
IF COL_LENGTH('dbo.TiepNhan', 'TUYENKHAMBENH_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD TUYENKHAMBENH_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'XACNHANCHIPHI_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD XACNHANCHIPHI_ID INT NULL;
IF COL_LENGTH('dbo.TiepNhan', 'XAPHUONG_ID') IS NULL ALTER TABLE dbo.TiepNhan ADD XAPHUONG_ID INT NULL;
GO

-- ─── K_LogKhoaBenhAn: bảng audit (sp_K_004 INSERT) ────────────────
IF OBJECT_ID('dbo.K_LogKhoaBenhAn', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.K_LogKhoaBenhAn (
        Id           INT IDENTITY(1,1) NOT NULL,
        TiepNhan_Id  INT      NULL,
        BenhAn_Id    INT      NULL,
        BenhNhan_Id  INT      NULL,
        NgayKhoa     DATETIME NULL,
        CONSTRAINT PK_K_LogKhoaBenhAn PRIMARY KEY (Id)
    );
END;
GO

-- ─── K_BenhNhan_Kios_VP: bảng tracking BN từ Kiosk (sp_K_004) ────
IF OBJECT_ID('dbo.K_BenhNhan_Kios_VP', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.K_BenhNhan_Kios_VP (
        Id                  INT IDENTITY(1,1) NOT NULL,
        BenhNhan_ID         INT          NULL,
        TiepNhan_ID_Old     INT          NULL,
        TiepNhan_ID_New     INT          NULL,
        CLSYeuCau_ID_Old    INT          NULL,
        CLSYeuCau_ID_New    INT          NULL,
        PhongBan_Id         INT          NULL,
        DichVu_Id           INT          NULL,
        DoiTuong_Id         INT          NULL,
        NgayTao             DATETIME     NULL,
        NgayTiepNhan        DATETIME     NULL,
        NguoiTao            INT          NULL,
        TrangThai           NVARCHAR(50) NULL,
        GhiChu_ThongTuyen   NVARCHAR(500) NULL,
        CONSTRAINT PK_K_BenhNhan_Kios_VP PRIMARY KEY (Id)
    );
END;
GO

PRINT 'OK: 06b_schema_his_light_extras.sql applied';
GO
