-- ════════════════════════════════════════════════════════════════
-- 21_seed_dm_hangdoi.sql
-- Seed dbo.DM_HangDoi.
-- Auto-generated by _scripts/clone_data.py at 2026-05-12T09:01:48.
-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── DM_HangDoi ─── 
SET IDENTITY_INSERT dbo.DM_HangDoi ON;
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 1)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (1, N'Tiếp Nhận', N'Tiếp Nhận', N'', 0, '2024-12-06 10:19:29', 1, NULL, NULL, 0, 2, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 2)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (2, N'Ưu Tiên', N'Ưu Tiên', N'', 0, '2024-12-06 10:19:47', 1, '2025-12-26 14:24:15', 1, 0, 11, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 3)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (3, N'Khu Khám Bệnh', N'Khu Khám Bệnh', NULL, 0, '2024-12-06 10:20:03', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 4)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (4, N'Thu Viện Phí', N'Thu Viện Phí', NULL, 0, '2024-12-06 10:20:16', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 5)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (5, N'Nhà Thuốc', N'Nhà Thuốc', NULL, 0, '2024-12-06 10:20:31', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 6)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (6, N'Lấy mẫu Xét Nghiệm', N'Lấy mẫu Xét Nghiệm', NULL, 0, '2024-12-06 10:20:44', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 7)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (7, N'Siêu Âm', N'Siêu Âm', NULL, 0, '2024-12-06 10:20:50', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 8)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (8, N'XQuang', N'XQuang', NULL, 0, '2024-12-06 10:20:55', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 9)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (9, N'Đo loãng xương', N'Đo loãng xương', NULL, 0, '2024-12-07 11:16:30', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 10)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (10, N'CT', N'CT', NULL, 0, '2024-12-07 11:18:03', 1, '2025-12-18 11:06:44', 1, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 11)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (11, N'Tiếp nhận căn cước', N'Tiếp nhận căn cước', NULL, 1, '2024-12-11 22:25:21', 1, '2024-12-13 11:26:10', 1, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 12)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (12, N'cntt', N'phòng công nghệ tin', NULL, 0, '2024-12-17 09:02:40', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 13)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (13, N'test', N'testkham4', NULL, 0, '2024-12-17 09:18:49', 1, '2024-12-17 09:27:09', 1, 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 14)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (14, N'KNP', N'Khoa ngoại phụ', NULL, 0, '2025-06-25 11:38:31', 1, NULL, NULL, 0, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_HangDoi WHERE HangDoi_Id = 19)
  INSERT INTO dbo.DM_HangDoi (HangDoi_Id, MaHangDoi, TenHangDoi, KyTuSTT, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy, Sound_Id_KyTu, PhongBanEhospital_Id) VALUES (19, N'132322', N'123232', NULL, 0, '2025-12-18 11:09:32', 1, '2025-12-18 11:09:09', 1, 1, NULL, NULL);
SET IDENTITY_INSERT dbo.DM_HangDoi OFF;
GO


PRINT 'OK: 21_seed_dm_hangdoi.sql';
GO
