-- ════════════════════════════════════════════════════════════════
-- 22_seed_dm_phongban.sql
-- Seed dbo.DM_PhongBan + dbo.DM_PhongBanLoaiPhongBan.
-- Auto-generated by _scripts/clone_data.py at 2026-05-12T09:01:48.
-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── DM_PhongBanLoaiPhongBan ─── 
SET IDENTITY_INSERT dbo.DM_PhongBanLoaiPhongBan ON;
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 1)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (1, N'Tiếp nhận', N'Quầy tiếp nhận', N'0', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 2)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (2, N'Khám bệnh', N'Khu Khám bệnh', N'1', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 3)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (3, N'Xét nghiệm', N'Khu xét nghiệm', N'2', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 4)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (4, N'Siêu âm', N'Khu Siêu âm', N'3', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 5)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (5, N'XQuang', N'Khu XQuang', N'4', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 6)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (6, N'Nội Soi', N'Khu Nội soi', N'5', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 7)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (7, N'CDHA khác', N'Khu CDHA khác', N'6', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 8)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (8, N'Viện phí', N'Quầy viện phí', N'7', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 9)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (9, N'Nhà thuốc', N'Nhà thuốc BV', N'8', 0, 0, NULL, NULL, NULL, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBanLoaiPhongBan WHERE LoaiPhongBan_Id = 10)
  INSERT INTO dbo.DM_PhongBanLoaiPhongBan (LoaiPhongBan_Id, TenLoaiPhongBan, TenLoaiPhongBanDayDu, STTPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa) VALUES (10, N'Khoa ngoại phụ', N'Khoa ngoại phụ', N'9', 0, 0, NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT dbo.DM_PhongBanLoaiPhongBan OFF;
GO

-- ─── DM_PhongBan ─── 
SET IDENTITY_INSERT dbo.DM_PhongBan ON;
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 1)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (1, N'Quầy tiếp nhận', N'Quầy Tiếp Nhận', NULL, NULL, 1, 0, 0, '2024-12-06 10:15:45', 1, NULL, NULL, NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 2)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (2, N'Phòng khám 1', N'Phòng Khám 1', NULL, NULL, 2, 0, 0, '2024-12-06 10:16:10', 1, '2025-12-18 09:52:11', 1, N'', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 3)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (3, N'Phòng Khám 2', N'Phòng Khám 2', NULL, NULL, 2, 0, 0, '2024-12-06 10:16:21', 1, NULL, NULL, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 4)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (4, N'Phòng Khám 3', N'Phòng Khám 3', NULL, NULL, 2, 0, 0, '2024-12-06 10:16:32', 1, NULL, NULL, NULL, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 5)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (5, N'Phòng Lấy Mẫu XN', N'Phòng Lấy Mẫu Xét Nghiệm', NULL, NULL, 3, 0, 0, '2024-12-06 10:17:17', 1, NULL, NULL, NULL, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 6)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (6, N'Phòng Siêu Âm 1', N'Phòng Siêu Âm 1', NULL, NULL, 4, 0, 0, '2024-12-06 10:17:33', 1, '2025-07-22 14:51:11', 1, NULL, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 7)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (7, N'Phòng X Quang', N'Phòng X Quang', NULL, NULL, 5, 0, 0, '2024-12-06 10:17:56', 1, NULL, NULL, NULL, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 8)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (8, N'Phòng Thu Viện Phí', N'Phòng Thu Viện Phí', NULL, NULL, 8, 0, 0, '2024-12-06 10:18:31', 1, NULL, NULL, NULL, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 9)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (9, N'Nhà Thuốc Bệnh Viện', N'Nhà Thuốc Bệnh Viện', NULL, NULL, 9, 0, 0, '2024-12-06 10:18:51', 1, NULL, NULL, NULL, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 10)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (10, N'Phòng Siêu Âm 2', N'Phòng Siêu Âm 2', NULL, NULL, 4, 0, 0, '2024-12-07 10:58:52', 1, NULL, NULL, NULL, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 11)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (11, N'Đo Loãng Xương', N'Đo Loãng Xương', NULL, NULL, 7, 0, 0, '2024-12-07 11:15:52', 1, '2024-12-12 22:09:36', 1, NULL, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 12)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (12, N'Phòng CT', N'Phòng CT', NULL, NULL, 7, 0, 0, '2024-12-07 11:19:34', 1, '2024-12-14 08:30:34', 1, NULL, 217);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 13)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (13, N'phongkham4', N'phongkham4test', NULL, NULL, 2, 0, 1, '2024-12-17 09:20:49', 1, '2024-12-17 09:26:44', 1, NULL, 219);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 14)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (14, N'Phòng khám yêu cầu', N'Phòng khám yêu cầu', NULL, NULL, 2, 0, 0, '2025-02-05 10:57:25', 1, NULL, NULL, NULL, 220);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 15)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (15, N'KNP', N'Khoa ngoại phụ', NULL, NULL, 10, 0, 0, '2025-06-25 11:40:55', 1, '2025-06-25 11:43:35', 1, NULL, 221);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 17)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (17, N'1', N'1', NULL, NULL, 2, 1, 1, '2025-12-18 10:10:48', 1, '2025-12-18 10:21:03', 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 18)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (18, N'2', N'1', NULL, NULL, 1, 0, 1, '2025-12-18 10:22:18', 1, '2025-12-18 10:23:01', 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 19)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (19, N'1', N'1', NULL, NULL, 1, 0, 1, '2025-12-18 10:26:39', 1, '2025-12-18 10:28:03', 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 20)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (20, N'hahaha', N'1', NULL, NULL, 1, 0, 1, '2025-12-18 10:26:51', 1, '2025-12-18 10:28:11', 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 21)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (21, N'3', N'3', NULL, NULL, 2, 0, 1, '2025-12-18 10:28:21', 1, '2025-12-18 10:28:16', 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 22)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (22, N'1', N'1', NULL, NULL, 2, 0, 1, '2025-12-18 10:29:30', 1, '2025-12-18 10:29:03', 1, NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_PhongBan WHERE PhongBan_Id = 23)
  INSERT INTO dbo.DM_PhongBan (PhongBan_Id, TenPhongBan, TenPhongBanDayDu, PhongBanEhospital_Id, STTPhongBan, LoaiPhongBan, TamNgung, Huy, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, MoTa, Sound_Id_PhongBan) VALUES (23, NULL, NULL, NULL, NULL, 0, 0, 1, '2025-12-18 10:54:31', 1, '2025-12-18 10:57:18', 1, NULL, NULL);
SET IDENTITY_INSERT dbo.DM_PhongBan OFF;
GO


PRINT 'OK: 22_seed_dm_phongban.sql';
GO
