-- ════════════════════════════════════════════════════════════════
-- 23_seed_users.sql
-- Seed dbo.Sys_Users (password giữ nguyên encrypted blob, plaintext='123') + dbo.Sys_Users_PhongBan.
-- Auto-generated by _scripts/clone_data.py at 2026-05-12T09:01:48.
-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── Sys_Users (29 rows, plaintext password='123') ─── 
SET IDENTITY_INSERT dbo.Sys_Users ON;
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 1)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (1, N'ADMIN', N'ADMINISTRATOR', N'&&&', 1, 0, 1, '2023-12-06 20:35:40', NULL, NULL, 0, N'Server', N'ADMIN', N'ADMIN', N'ADMIN', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 2)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (2, N'kios', N'kiosk', N'&&&', NULL, 0, 1, '2024-12-07 08:57:13', 1, '2025-03-05 17:03:55', 0, NULL, N'userver', N'kios', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 3)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (3, N'userver', N'Server Tổng', N'&&&', NULL, 0, 1, '2024-12-07 08:59:41', 1, '2024-12-07 10:06:59', 0, N'Server', N'userver', N'userver', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 4)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (4, N'tiepnhan', N'Tiếp Nhận', N'&&&', NULL, 0, 1, '2024-12-07 09:02:04', 1, '2024-12-14 14:37:34', 0, NULL, N'userver', N'tiepnhan', N'userver', N'tivitiepnhan                                                                                                                                                                                                                                              ', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 5)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (5, N'phongkham1', N'Phòng Khám 1', N'&&&', NULL, 0, 1, '2024-12-07 09:03:22', NULL, NULL, 0, NULL, N'userver', N'phongkham1', N'userver', N'tivikhambenh', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 6)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (6, N'sieuam2', N'Phòng siêu âm 2', N'&&&', NULL, 0, 1, '2024-12-07 10:50:24', NULL, NULL, 0, NULL, N'userver', N'sieuam2', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 7)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (7, N'phongkham2', N'Phòng Khám 2', N'&&&', NULL, 0, 1, '2024-12-07 11:07:59', NULL, NULL, 0, NULL, N'userver', N'phongkham1', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 8)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (8, N'doloangxuong', N'Phòng Đo Loãng Xương', N'&&&', NULL, 0, 1, '2024-12-07 11:14:50', NULL, NULL, 0, NULL, N'userver', N'doloangxuong', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 9)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (9, N'phongct', N'Phòng CT', N'&&&', NULL, 0, 1, '2024-12-07 11:16:43', NULL, NULL, 0, NULL, N'userver', N'phongct', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 10)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (10, N'sieuam1', N'Phòng siêu âm 1', N'&&&', NULL, 0, 1, '2024-12-07 11:23:10', 1, '2025-07-30 14:22:56', 0, NULL, N'userver', N'nhanbenhCLS', N'userver', N'tivicls', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 11)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (11, N'xquang', N'Phòng X Quang', N'&&&', NULL, 0, 1, '2024-12-07 11:32:25', NULL, NULL, 0, NULL, N'userver', N'xquang', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 12)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (12, N'vienphi', N'Phòng Viện Phí', N'&&&', NULL, 0, 1, '2024-12-07 14:57:08', NULL, NULL, 0, NULL, N'userver', N'vienphi', N'userver', N'tivivienphi', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 13)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (13, N'phongkham3', N'Phòng Khám 3', N'&&&', NULL, 0, 1, '2024-12-07 16:18:37', NULL, NULL, 0, NULL, N'userver', N'phongkham3', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 14)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (14, N'nhathuoc', N'Nhà thuốc bệnh viện', N'&&&', NULL, 0, 1, '2024-12-09 22:01:10', NULL, NULL, 0, NULL, N'userver', N'nhathuoc', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 15)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (15, N'phonglaymau', N'Phòng Lấy Mẫu', N'&&&', NULL, 0, 1, '2024-12-11 07:48:44', 1, '2024-12-13 10:13:24', 0, N'Server', N'phonglaymau', N'phonglaymau', N'phonglaymau', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 16)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (16, N'nhanbenhCLS', N'Nhận bệnh CLS Nội Trú', N'&&&', NULL, 0, 1, '2024-12-13 14:25:35', 1, '2025-07-30 14:33:11', 0, NULL, N'userver', N'nhanbenhCLS', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 17)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (17, N'VienPhi', N'Viện phí', N'&&&', NULL, 1, 1, '2024-12-13 15:55:01', 1, '2025-07-22 14:44:32', 0, N'Server', N'VienPhi', N'VienPhi', N'VienPhi', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 18)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (18, N'Nhathuoc', N'Nhà Thuốc', N'&&&', NULL, 0, 1, '2024-12-14 09:25:37', NULL, NULL, 0, NULL, N'userver', N'Nhathuoc', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 19)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (19, N'cntt', N'cnttt', N'&&&', NULL, 0, 1, '2024-12-17 08:56:01', NULL, NULL, 0, NULL, N'userver', N'cntt', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 20)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (20, N'test', N'test01', N'&&&', NULL, 0, 1, '2024-12-17 09:16:41', 1, '2024-12-17 09:24:52', 1, NULL, N'userver', N'test', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 21)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (21, N'phongyeucau', N'Phòng khám Yêu cầu', N'&&&', NULL, 0, 1, '2025-02-05 10:56:53', NULL, NULL, 0, NULL, N'userver', N'phongyeucau', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 22)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (22, N'khambenh', N'User khoa Khám bệnh', N'&&&', NULL, 0, 1, '2025-03-27 10:16:10', NULL, NULL, 0, NULL, N'userver', N'khambenh', N'userver', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 23)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (23, N'khoangoaiphu', N'khoangoaiphu', N'&&&', NULL, 0, 1, '2025-06-25 11:36:50', 1, '2025-06-25 11:58:39', 0, N'Server', N'khoangoaiphu', N'khoangoaiphu', N'khoangoaiphu', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 24)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (24, N'quayvienphi1', N'quầy viện phí 1', N'&&&', NULL, 0, 1, '2025-07-22 14:49:04', NULL, NULL, 0, NULL, N'vienphi', N'vienphi', N'vienphi', NULL, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 26)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (26, N'tivitiepnhan', N'Tivi tiếp nhận', N'&&&', NULL, 0, 1, '2025-12-26 15:35:53', NULL, NULL, 0, NULL, NULL, NULL, NULL, N'tivitiepnhan                                                                                                                                                                                                                                              ', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 27)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (27, N'amthanhtiepnhan', N'Âm thanh tiếp nhận', N'&&&', NULL, 0, 1, '2025-12-26 16:23:11', NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, N'amthanhtiepnhan');
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 28)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (28, N'tivikhambenh', N'Tivi Khám bệnh', N'&&&', NULL, 0, 1, '2025-12-27 09:35:20', NULL, NULL, 0, NULL, NULL, NULL, NULL, N'tivikhambenh', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 29)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (29, N'tivicls', N'Tivi cận lâm sàng', N'&&&', NULL, 0, 1, '2025-12-27 09:35:31', NULL, NULL, 0, NULL, NULL, NULL, NULL, N'tivicls', NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users WHERE User_Id = 30)
  INSERT INTO dbo.Sys_Users (User_Id, UserCode, UserName, Password, BenhVien_Id, TamNgung, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat, Huy, MoTaMay, MoTaKetNoiMay, MoTaKetNoiTiVi, MoTaKetNoiAmThanh, TenTivi, TenAmThanh) VALUES (30, N'tivivienphi', N'Tivi viện phí', N'&&&', NULL, 0, 1, '2025-12-27 09:35:50', NULL, NULL, 0, NULL, NULL, NULL, NULL, N'tivivienphi', NULL);
SET IDENTITY_INSERT dbo.Sys_Users OFF;
GO

-- ─── Sys_Users_PhongBan ─── 
SET IDENTITY_INSERT dbo.Sys_Users_PhongBan ON;
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 19)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (19, 6, NULL, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 20)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (20, 6, 10, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 21)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (21, 7, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 22)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (22, 7, 3, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 23)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (23, 8, NULL, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 24)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (24, 8, 11, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 27)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (27, 10, NULL, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 28)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (28, 10, 6, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 29)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (29, 5, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 30)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (30, 5, 2, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 31)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (31, 11, NULL, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 32)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (32, 11, 7, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 33)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (33, 12, NULL, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 34)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (34, 12, 8, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 35)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (35, 13, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 36)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (36, 13, 4, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 37)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (37, 14, NULL, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 38)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (38, 14, 9, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 45)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (45, 15, NULL, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 46)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (46, 15, 5, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 67)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (67, 2, NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 68)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (68, 2, 1, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 92)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (92, 17, NULL, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 93)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (93, 17, 8, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 94)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (94, 18, NULL, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 95)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (95, 18, 9, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 106)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (106, 9, NULL, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 107)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (107, 9, 12, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 126)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (126, 19, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 127)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (127, 19, 2, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 129)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (129, 20, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 130)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (130, 20, 13, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 143)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (143, 21, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 144)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (144, 21, 14, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 147)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (147, 22, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 148)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (148, 22, NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 149)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (149, 22, 2, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 152)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (152, 23, NULL, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 153)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (153, 23, 15, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 156)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (156, 16, NULL, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 157)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (157, 16, 6, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 180)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (180, 4, NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 181)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (181, 4, NULL, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 182)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (182, 4, 1, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 185)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (185, 26, NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 186)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (186, 26, 1, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 189)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (189, 28, NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 190)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (190, 28, 2, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 193)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (193, 29, NULL, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 194)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (194, 29, 6, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 195)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (195, 30, NULL, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 196)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (196, 30, 8, NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 199)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (199, 1, NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Sys_Users_PhongBan WHERE User_PhongBan_Id = 200)
  INSERT INTO dbo.Sys_Users_PhongBan (User_PhongBan_Id, User_Id, PhongBan_Id, HangDoi_Id) VALUES (200, 1, 1, NULL);
SET IDENTITY_INSERT dbo.Sys_Users_PhongBan OFF;
GO


PRINT 'OK: 23_seed_users.sql';
GO
