-- ════════════════════════════════════════════════════════════════
-- 24_seed_menu.sql
-- Seed dbo.Menu + dbo.Permission.
-- Auto-generated by _scripts/clone_data.py at 2026-05-12T09:01:48.
-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── Menu ─── 
SET IDENTITY_INSERT dbo.Menu ON;
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 1)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (1, N'ribbonPage1', N'Tiếp Nhận', NULL, 0, '2024-10-04 09:02:59', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 2)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (2, N'ribbonPage2', N'Khám bệnh', NULL, 0, '2024-10-04 09:03:13', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 3)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (3, N'ribbonPage3', N'Cận lâm sàng', NULL, 0, '2024-10-04 09:03:26', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 4)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (4, N'ribbonPage4', N'Danh mục', NULL, 0, '2024-10-04 09:03:37', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 5)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (5, N'ribbonPage5', N'Hệ thống', NULL, 0, '2024-10-04 09:03:46', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 6)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (6, N'ribbonPageGroup1', N'Group Kiosk', 1, 0, '2024-10-04 09:05:15', 1, '2025-12-02 22:30:55', 1, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 7)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (7, N'ribbonPageGroup3', N'Group Tiếp nhận', 1, 0, '2024-10-04 09:05:37', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 8)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (8, N'ribbonPageGroup2', N'Group Khám bệnh', 2, 0, '2024-10-04 09:05:52', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 9)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (9, N'ribbonPageGroup4', N'Group Xét nghiệm', 3, 0, '2024-10-04 09:06:10', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 10)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (10, N'ribbonPageGroup5', N'Group Chẩn đoán hình ảnh', 3, 0, '2024-10-04 09:06:23', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 11)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (11, N'ribbonPageGroup6', N'Group Hệ thống danh mục', 4, 0, '2024-10-04 09:06:40', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 12)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (12, N'ribbonPageGroup7', N'Group Cá nhân', 5, 0, '2024-10-04 09:06:57', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 13)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (13, N'ribbonPageGroup8', N'Group Quản lý người dùng', 5, 0, '2024-10-04 09:07:11', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 14)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (14, N'ribbonPageGroup9', N'Group Quản lý hệ thống', 5, 0, '2024-10-04 09:07:32', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 15)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (15, N'barButtonItem1', N'Kiosk Tiếp nhận', 6, 0, '2024-10-04 09:07:48', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 16)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (16, N'barButtonItem3', N'Tivi Tiếp nhận', 6, 0, '2024-10-04 09:08:06', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 17)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (17, N'barButtonItem2', N'Quầy tiếp nhận', 7, 0, '2024-10-04 09:08:41', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 18)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (18, N'barButtonItem4', N'Quản lý khám bệnh', 8, 0, '2024-10-04 09:09:01', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 19)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (19, N'barButtonItem5', N'Tivi Khám bệnh', 8, 0, '2024-10-04 09:09:17', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 20)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (20, N'barButtonItem6', N'Quản lý hàng đợi lấy mẫu', 9, 0, '2024-10-04 09:09:38', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 21)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (21, N'barButtonItem7', N'Tivi Hàng đợi lấy mẫu', 9, 0, '2024-10-04 09:09:53', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 22)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (22, N'barButtonItem8', N'Nhận bệnh', 10, 0, '2024-10-04 09:10:18', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 23)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (23, N'barButtonItem9', N'Gọi bệnh', 10, 0, '2024-10-04 09:10:30', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 24)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (24, N'barButtonItem10', N'Tivi Hàng đợi CDHA', 10, 0, '2024-10-04 09:10:48', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 25)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (25, N'barButtonItem11', N'Danh mục phòng ban', 11, 0, '2024-10-04 09:11:15', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 26)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (26, N'barButtonItem12', N'Danh mục hàng đợi', 11, 0, '2024-10-04 09:11:33', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 27)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (27, N'barButtonItem13', N'Phân quyền User- Hàng đợi - Phòng ban', 11, 0, '2024-10-04 09:12:02', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 28)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (28, N'barButtonItem14', N'Nội dung đặc biệt', 11, 0, '2024-10-04 09:12:17', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 29)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (29, N'barButtonItem15', N'Đăng xuất', 12, 0, '2024-10-04 09:12:49', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 30)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (30, N'barButtonItem16', N'Đổi mật khẩu', 12, 0, '2024-10-04 09:13:12', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 31)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (31, N'barButtonItem17', N'Users', 13, 0, '2024-10-04 09:13:33', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 32)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (32, N'barButtonItem18', N'Menu', 13, 0, '2024-10-04 09:13:52', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 33)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (33, N'barButtonItem19', N'Phân quyền menu', 13, 0, '2024-10-04 09:14:16', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 34)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (34, N'barButtonItem20', N'Server', 14, 0, '2024-10-04 09:14:28', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 35)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (35, N'barButtonItem21', N'Âm thanh', 14, 0, '2024-10-04 09:14:38', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 36)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (36, N'barButtonItem22', N'Danh sách bệnh nhân', 14, 0, '2024-10-10 09:53:04', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 37)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (37, N'ribbonPage6', N'Viện Phí', NULL, 0, '2024-12-05 14:46:21', 1, '2025-12-02 22:33:55', 1, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 38)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (38, N'ribbonPageGroup10', N'Viện phí thao tác', 37, 0, '2024-12-05 14:47:00', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 39)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (39, N'barButtonItem23', N'Viện phí gọi bệnh', 38, 0, '2024-12-05 14:47:24', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 40)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (40, N'barButtonItem24', N'Viện phí tivi', 38, 0, '2024-12-05 14:47:40', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 41)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (41, N'ribbonPage7', N'Nhà thuốc', NULL, 0, '2024-12-09 21:59:23', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 42)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (42, N'ribbonPageGroup11', N'Nhà thuốc thao tác', 41, 0, '2024-12-09 21:59:56', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 43)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (43, N'barButtonItem25', N'Nhà thuốc gọi bệnh', 42, 0, '2024-12-09 22:00:13', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 44)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (44, N'barButtonItem26', N'Nhà thuốc tivi', 42, 0, '2024-12-09 22:00:28', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 45)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (45, N'ribbonPageGroup12', N'Group Bệnh nhân nội trú check in', 3, 0, '2024-12-13 14:24:35', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 46)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (46, N'barButtonItem27', N'Bệnh nhân nội trú check in CLS', 45, 0, '2024-12-13 14:24:49', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 47)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (47, N'barButtonItem28', N'Danh sách khám bệnh', 8, 0, '2025-03-27 10:14:59', 1, NULL, NULL, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.Menu WHERE Menu_Id = 48)
  INSERT INTO dbo.Menu (Menu_Id, MenuCode, MenuName, ParentMenu, TamNgung, NgayTao, NguoiTao, NgayCapNhat, NguoiCapNhat, Huy) VALUES (48, N'barButtonItem29', N'Thời gian thực hiện dịch vụ', 11, 0, '2025-08-28 13:17:01', 1, '2025-08-28 13:17:34', 1, 0);
SET IDENTITY_INSERT dbo.Menu OFF;
GO

-- ─── Permission ─── 
SET IDENTITY_INSERT dbo.Permission ON;
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 51)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (51, 3, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 52)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (52, 3, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 53)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (53, 3, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 54)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (54, 3, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 55)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (55, 3, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 56)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (56, 3, 34);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 57)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (57, 3, 35);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 58)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (58, 3, 36);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 59)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (59, 4, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 60)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (60, 4, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 61)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (61, 4, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 62)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (62, 4, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 63)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (63, 4, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 64)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (64, 4, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 65)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (65, 4, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 66)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (66, 4, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 67)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (67, 4, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 68)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (68, 4, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 130)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (130, 12, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 131)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (131, 12, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 132)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (132, 12, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 133)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (133, 12, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 134)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (134, 12, 37);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 135)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (135, 12, 38);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 136)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (136, 12, 39);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 137)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (137, 12, 40);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 146)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (146, 14, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 147)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (147, 14, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 148)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (148, 14, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 149)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (149, 14, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 150)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (150, 14, 41);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 151)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (151, 14, 42);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 152)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (152, 14, 43);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 153)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (153, 14, 44);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 221)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (221, 6, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 222)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (222, 6, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 223)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (223, 6, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 224)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (224, 6, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 225)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (225, 6, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 226)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (226, 6, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 227)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (227, 6, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 228)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (228, 6, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 229)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (229, 8, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 230)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (230, 8, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 231)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (231, 8, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 232)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (232, 8, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 233)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (233, 8, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 234)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (234, 8, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 235)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (235, 8, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 236)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (236, 8, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 237)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (237, 9, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 238)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (238, 9, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 239)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (239, 9, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 240)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (240, 9, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 241)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (241, 9, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 242)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (242, 9, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 243)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (243, 9, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 244)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (244, 9, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 245)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (245, 10, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 246)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (246, 10, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 247)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (247, 10, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 248)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (248, 10, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 249)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (249, 10, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 250)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (250, 10, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 251)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (251, 10, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 252)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (252, 10, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 253)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (253, 11, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 254)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (254, 11, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 255)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (255, 11, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 256)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (256, 11, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 257)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (257, 11, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 258)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (258, 11, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 259)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (259, 11, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 260)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (260, 11, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 261)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (261, 15, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 262)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (262, 15, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 263)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (263, 15, 20);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 264)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (264, 15, 21);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 265)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (265, 15, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 266)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (266, 15, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 267)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (267, 15, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 268)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (268, 15, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 269)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (269, 15, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 270)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (270, 15, 34);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 271)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (271, 15, 35);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 272)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (272, 15, 36);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 326)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (326, 18, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 327)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (327, 18, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 328)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (328, 18, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 329)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (329, 18, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 330)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (330, 18, 41);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 331)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (331, 18, 42);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 332)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (332, 18, 43);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 333)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (333, 18, 44);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 380)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (380, 20, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 381)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (381, 20, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 382)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (382, 20, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 383)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (383, 20, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 384)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (384, 20, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 385)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (385, 20, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 386)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (386, 20, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 387)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (387, 20, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 396)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (396, 22, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 397)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (397, 22, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 398)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (398, 22, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 399)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (399, 22, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 400)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (400, 22, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 401)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (401, 22, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 402)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (402, 22, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 403)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (403, 22, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 404)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (404, 22, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 405)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (405, 22, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 406)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (406, 22, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 407)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (407, 22, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 408)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (408, 22, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 409)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (409, 22, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 410)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (410, 22, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 458)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (458, 19, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 459)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (459, 19, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 460)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (460, 19, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 461)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (461, 19, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 462)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (462, 19, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 463)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (463, 19, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 464)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (464, 19, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 465)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (465, 19, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 466)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (466, 19, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 467)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (467, 19, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 468)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (468, 19, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 469)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (469, 19, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 470)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (470, 19, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 471)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (471, 19, 20);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 472)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (472, 19, 21);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 473)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (473, 19, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 474)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (474, 19, 22);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 475)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (475, 19, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 476)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (476, 19, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 477)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (477, 19, 45);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 478)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (478, 19, 46);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 479)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (479, 19, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 480)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (480, 19, 11);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 481)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (481, 19, 25);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 482)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (482, 19, 26);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 483)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (483, 19, 27);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 484)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (484, 19, 28);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 485)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (485, 19, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 486)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (486, 19, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 487)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (487, 19, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 488)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (488, 19, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 489)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (489, 19, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 490)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (490, 19, 31);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 491)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (491, 19, 32);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 492)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (492, 19, 33);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 493)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (493, 19, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 494)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (494, 19, 34);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 495)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (495, 19, 35);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 496)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (496, 19, 36);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 497)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (497, 19, 37);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 498)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (498, 19, 38);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 499)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (499, 19, 39);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 500)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (500, 19, 40);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 501)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (501, 19, 41);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 502)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (502, 19, 42);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 503)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (503, 19, 43);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 504)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (504, 19, 44);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 505)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (505, 5, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 506)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (506, 5, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 507)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (507, 5, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 508)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (508, 5, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 509)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (509, 5, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 510)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (510, 5, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 511)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (511, 5, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 512)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (512, 5, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 513)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (513, 5, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 514)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (514, 7, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 515)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (515, 7, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 516)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (516, 7, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 517)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (517, 7, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 518)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (518, 7, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 519)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (519, 7, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 520)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (520, 7, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 521)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (521, 7, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 522)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (522, 7, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 523)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (523, 13, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 524)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (524, 13, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 525)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (525, 13, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 526)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (526, 13, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 527)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (527, 13, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 528)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (528, 13, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 529)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (529, 13, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 530)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (530, 13, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 531)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (531, 13, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 532)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (532, 21, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 533)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (533, 21, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 534)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (534, 21, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 535)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (535, 21, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 536)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (536, 21, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 537)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (537, 21, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 538)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (538, 21, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 539)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (539, 21, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 540)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (540, 21, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 541)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (541, 23, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 542)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (542, 23, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 543)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (543, 23, 22);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 544)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (544, 23, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 545)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (545, 23, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 546)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (546, 23, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 547)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (547, 23, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 548)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (548, 23, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 549)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (549, 23, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 550)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (550, 23, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 551)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (551, 23, 34);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 552)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (552, 23, 35);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 553)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (553, 23, 36);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 554)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (554, 16, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 555)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (555, 16, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 556)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (556, 16, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 557)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (557, 16, 45);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 558)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (558, 16, 46);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 559)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (559, 16, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 560)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (560, 16, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 561)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (561, 16, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 562)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (562, 16, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 611)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (611, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 612)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (612, 1, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 613)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (613, 1, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 614)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (614, 1, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 615)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (615, 1, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 616)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (616, 1, 17);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 617)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (617, 1, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 618)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (618, 1, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 619)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (619, 1, 18);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 620)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (620, 1, 19);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 621)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (621, 1, 47);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 622)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (622, 1, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 623)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (623, 1, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 624)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (624, 1, 20);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 625)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (625, 1, 21);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 626)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (626, 1, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 627)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (627, 1, 22);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 628)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (628, 1, 23);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 629)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (629, 1, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 630)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (630, 1, 45);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 631)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (631, 1, 46);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 632)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (632, 1, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 633)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (633, 1, 11);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 634)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (634, 1, 25);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 635)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (635, 1, 26);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 636)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (636, 1, 27);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 637)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (637, 1, 28);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 638)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (638, 1, 48);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 639)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (639, 1, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 640)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (640, 1, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 641)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (641, 1, 29);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 642)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (642, 1, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 643)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (643, 1, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 644)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (644, 1, 31);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 645)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (645, 1, 32);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 646)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (646, 1, 33);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 647)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (647, 1, 14);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 648)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (648, 1, 34);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 649)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (649, 1, 35);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 650)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (650, 1, 36);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 651)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (651, 1, 37);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 652)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (652, 1, 38);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 653)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (653, 1, 39);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 654)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (654, 1, 40);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 655)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (655, 1, 41);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 656)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (656, 1, 42);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 657)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (657, 1, 43);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 658)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (658, 1, 44);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 659)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (659, 2, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 660)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (660, 2, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 661)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (661, 2, 15);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 662)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (662, 26, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 663)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (663, 26, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 664)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (664, 26, 16);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 665)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (665, 30, 37);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 666)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (666, 30, 38);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 667)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (667, 30, 40);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 668)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (668, 29, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 669)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (669, 29, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 670)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (670, 29, 24);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 671)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (671, 28, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 672)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (672, 28, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Permission_Id = 673)
  INSERT INTO dbo.Permission (Permission_Id, User_Id, Menu_Id) VALUES (673, 28, 19);
SET IDENTITY_INSERT dbo.Permission OFF;
GO


PRINT 'OK: 24_seed_menu.sql';
GO
