-- ════════════════════════════════════════════════════════════════
-- 25_seed_misc.sql
-- Seed DM_NoiDungDacBiet + DM_ThoiGianDichVu + K_DM_DoiTuongUuTien.
-- Auto-generated by _scripts/clone_data.py at 2026-05-12T09:01:48.
-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── DM_NoiDungDacBiet ─── 
SET IDENTITY_INSERT dbo.DM_NoiDungDacBiet ON;
SET IDENTITY_INSERT dbo.DM_NoiDungDacBiet OFF;
GO

-- ─── DM_ThoiGianDichVu — SKIPPED (FK constraint to DM_DichVu, seed sau khi 26 chạy nếu cần) ─── 
-- DM_ThoiGianDichVu có 110 rows ở DB cũ. FK -> DM_DichVu. Skip để tránh fail.
-- Có thể seed thủ công sau khi đã load DM_DichVu top500.
-- ─── K_DM_DoiTuongUuTien ─── 
SET IDENTITY_INSERT dbo.K_DM_DoiTuongUuTien ON;
IF NOT EXISTS (SELECT 1 FROM dbo.K_DM_DoiTuongUuTien WHERE DoiTuongUuTien_Id = 1)
  INSERT INTO dbo.K_DM_DoiTuongUuTien (DoiTuongUuTien_Id, TenDoiTuong, Huy) VALUES (1, N'Trường hợp cấp cứu', 0);
IF NOT EXISTS (SELECT 1 FROM dbo.K_DM_DoiTuongUuTien WHERE DoiTuongUuTien_Id = 2)
  INSERT INTO dbo.K_DM_DoiTuongUuTien (DoiTuongUuTien_Id, TenDoiTuong, Huy) VALUES (2, N'Trẻ em dưới 6 tuổi', 0);
IF NOT EXISTS (SELECT 1 FROM dbo.K_DM_DoiTuongUuTien WHERE DoiTuongUuTien_Id = 3)
  INSERT INTO dbo.K_DM_DoiTuongUuTien (DoiTuongUuTien_Id, TenDoiTuong, Huy) VALUES (3, N'Người khuyết tật nặng', 0);
IF NOT EXISTS (SELECT 1 FROM dbo.K_DM_DoiTuongUuTien WHERE DoiTuongUuTien_Id = 4)
  INSERT INTO dbo.K_DM_DoiTuongUuTien (DoiTuongUuTien_Id, TenDoiTuong, Huy) VALUES (4, N'Người từ đủ 80 tuổi trở lên', 0);
IF NOT EXISTS (SELECT 1 FROM dbo.K_DM_DoiTuongUuTien WHERE DoiTuongUuTien_Id = 5)
  INSERT INTO dbo.K_DM_DoiTuongUuTien (DoiTuongUuTien_Id, TenDoiTuong, Huy) VALUES (5, N'Phụ nữ có thai', 0);
IF NOT EXISTS (SELECT 1 FROM dbo.K_DM_DoiTuongUuTien WHERE DoiTuongUuTien_Id = 6)
  INSERT INTO dbo.K_DM_DoiTuongUuTien (DoiTuongUuTien_Id, TenDoiTuong, Huy) VALUES (6, N'Người có công với cách mạng', 0);
SET IDENTITY_INSERT dbo.K_DM_DoiTuongUuTien OFF;
GO


PRINT 'OK: 25_seed_misc.sql';
GO
