-- ════════════════════════════════════════════════════════════════
-- 27_seed_dm_doituong.sql
-- Seed dbo.DM_DoiTuong (manual — không có ở DB cũ).
-- Auto-generated by _scripts/clone_data.py at 2026-05-12T09:01:49.
-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── DM_DoiTuong (6 rows) ─── 
IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'DV')
  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (N'DV', N'Dịch vụ', 0.0, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'BH80')
  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (N'BH80', N'BHYT 80%', 0.8, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'BH95')
  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (N'BH95', N'BHYT 95%', 0.95, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'BH100')
  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (N'BH100', N'BHYT 100%', 1.0, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'BH5N')
  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (N'BH5N', N'BHYT 5 năm (80% -> 100%)', 0.8, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'BHCD')
  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (N'BHCD', N'BHYT chuyển đến', 0.8, 0);

PRINT 'OK: 27_seed_dm_doituong.sql';
GO
