-- ════════════════════════════════════════════════════════════════
-- 99_stub_views.sql
-- Stub views for tables NOT cloned into QMS_DA (PRODUCT_HIS legacy
-- HOADON/VIENPHI/REQUEST*, eHospital_SanNhi*, etc.). Each stub is
-- WHERE 1=0 so always returns 0 rows. Lets ported SPs compile and
-- execute without throwing 'Invalid object name' or 'Invalid column'.
-- ════════════════════════════════════════════════════════════════

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
USE QMS_DA;
GO

-- ─── stub: HIS_TT_HOADON ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_HOADON', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_HOADON;
GO
CREATE VIEW dbo.HIS_TT_HOADON AS
SELECT * FROM (SELECT
  [HOADON_ID] = CAST(NULL AS INT),
  [TIEPNHAN_ID] = CAST(NULL AS INT),
  [BENHNHAN_ID] = CAST(NULL AS INT),
  [DOITUONG_ID] = CAST(NULL AS INT),
  [NGAYHOADON] = CAST(NULL AS DATETIME),
  [TONGTIEN] = CAST(NULL AS DECIMAL(18,2)),
  [TONGCHIPHI] = CAST(NULL AS DECIMAL(18,2)),
  [TRANGTHAI] = CAST(NULL AS VARCHAR(50)),
  [HUYHOADON] = CAST(NULL AS CHAR(1))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_VIENPHI ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_VIENPHI', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_VIENPHI;
GO
CREATE VIEW dbo.HIS_TT_VIENPHI AS
SELECT * FROM (SELECT
  [VIENPHI_ID] = CAST(NULL AS INT),
  [TIEPNHAN_ID] = CAST(NULL AS INT),
  [BENHAN_ID] = CAST(NULL AS INT),
  [BENHNHAN_ID] = CAST(NULL AS INT),
  [DOTDIEUTRI_ID] = CAST(NULL AS INT),
  [KHAMBENH_ID] = CAST(NULL AS INT),
  [REF_ID] = CAST(NULL AS INT),
  [REF_TABLE] = CAST(NULL AS VARCHAR(50)),
  [LOAIGIA_ID] = CAST(NULL AS INT),
  [DICHVU_ID] = CAST(NULL AS INT),
  [DUOC_ID] = CAST(NULL AS INT),
  [LOAI_CHIPHI] = CAST(NULL AS VARCHAR(20)),
  [SOLUONG] = CAST(NULL AS INT),
  [DONGIA_DOANHTHU] = CAST(NULL AS DECIMAL(18,2)),
  [THANHTIEN_DOANHTHU] = CAST(NULL AS DECIMAL(18,2)),
  [BHYT_TL] = CAST(NULL AS DECIMAL(8,4)),
  [BHYT_DONGIA] = CAST(NULL AS DECIMAL(18,2)),
  [BHYT_THANHTIEN] = CAST(NULL AS DECIMAL(18,2)),
  [BHYT_DONGIA_CHITRA] = CAST(NULL AS DECIMAL(18,2)),
  [BHYT_THANHTIEN_CHITRA] = CAST(NULL AS DECIMAL(18,2)),
  [BENHNHAN_PHAITHANHTOAN] = CAST(NULL AS DECIMAL(18,2)),
  [GIATRI_HOADON] = CAST(NULL AS DECIMAL(18,2)),
  [GIATRI_HOADON_DATHANHTOAN] = CAST(NULL AS DECIMAL(18,2)),
  [GIATRI_BIENLAI] = CAST(NULL AS DECIMAL(18,2)),
  [GIATRI_BIENLAI_DATHANHTOAN] = CAST(NULL AS DECIMAL(18,2)),
  [GIATRI_BENHNHAN_DATHANHTOAN] = CAST(NULL AS DECIMAL(18,2)),
  [GIATRI_THATTHU] = CAST(NULL AS DECIMAL(18,2)),
  [MIENGIAM_TL] = CAST(NULL AS DECIMAL(8,4)),
  [MIENGIAM_GIATRI] = CAST(NULL AS DECIMAL(18,2)),
  [NGANSACH_TL] = CAST(NULL AS DECIMAL(8,4)),
  [NGANSACH_GIATRI] = CAST(NULL AS DECIMAL(18,2)),
  [TAITRO_TL] = CAST(NULL AS DECIMAL(8,4)),
  [TAITRO_GIATRI] = CAST(NULL AS DECIMAL(18,2)),
  [BHTN_TL] = CAST(NULL AS DECIMAL(8,4)),
  [BHTN_DONGIA] = CAST(NULL AS DECIMAL(18,2)),
  [BHTN_THANHTIEN] = CAST(NULL AS DECIMAL(18,2)),
  [BHTN_DONGIA_CHITRA] = CAST(NULL AS DECIMAL(18,2)),
  [BHTN_THANHTIEN_CHITRA] = CAST(NULL AS DECIMAL(18,2)),
  [DUOCPHEPTHUCHIEN] = CAST(NULL AS CHAR(1)),
  [HUY] = CAST(NULL AS CHAR(1)),
  [DATHANHTOAN] = CAST(NULL AS CHAR(1)),
  [DATHUCHIEN] = CAST(NULL AS CHAR(1)),
  [KHONGTHUTIEN] = CAST(NULL AS CHAR(1)),
  [BHYTDONGTIEN] = CAST(NULL AS DECIMAL(18,2)),
  [DUYET] = CAST(NULL AS CHAR(1)),
  [HOADON_ID] = CAST(NULL AS INT),
  [ACTIVE] = CAST(NULL AS CHAR(1)),
  [TYLE_VAT] = CAST(NULL AS DECIMAL(8,4)),
  [GIAVON] = CAST(NULL AS DECIMAL(18,2)),
  [BANGGIA_ID] = CAST(NULL AS INT),
  [BENHVIEN_ID] = CAST(NULL AS INT),
  [NGUOITAO_ID] = CAST(NULL AS INT),
  [NGAYTAO] = CAST(NULL AS DATETIME),
  [NGUOICAPNHAT_ID] = CAST(NULL AS INT),
  [NGAYCAPNHAT] = CAST(NULL AS DATETIME),
  [DONGIA_BHYT_BANDAU] = CAST(NULL AS DECIMAL(18,2)),
  [DONGIADOANHTHU_BANDAU] = CAST(NULL AS DECIMAL(18,2)),
  [YEUCAUVP] = CAST(NULL AS CHAR(1)),
  [DOITUONG_HUONG_ID] = CAST(NULL AS INT),
  [SOBHYT_HUONG_ID] = CAST(NULL AS INT),
  [DICHVU_TL] = CAST(NULL AS DECIMAL(8,4)),
  [SOLONHAP_ID] = CAST(NULL AS INT),
  [THANHTIEN] = CAST(NULL AS DECIMAL(18,2)),
  [TRANGTHAI] = CAST(NULL AS VARCHAR(50)),
  [BHYT_DONGIA_CONGKHAM_DAU] = CAST(NULL AS DECIMAL(18,2)),
  [BHYT_CONGKHAM_DAU_TYLE] = CAST(NULL AS DECIMAL(8,4))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_REQUEST ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_REQUEST', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_REQUEST;
GO
CREATE VIEW dbo.HIS_TT_REQUEST AS
SELECT * FROM (SELECT
  [ID] = CAST(NULL AS INT),
  [REQUEST_ID] = CAST(NULL AS INT),
  [TIEPNHAN_ID] = CAST(NULL AS INT),
  [BENHNHAN_ID] = CAST(NULL AS INT),
  [NGAYREQUEST] = CAST(NULL AS DATETIME),
  [TRANGTHAI] = CAST(NULL AS VARCHAR(50)),
  [PROCESS_CODE] = CAST(NULL AS VARCHAR(50)),
  [PARA] = CAST(NULL AS NVARCHAR(MAX)),
  [CURR_STATE_CODE] = CAST(NULL AS VARCHAR(50)),
  [ISACTIVE] = CAST(NULL AS CHAR(1))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_REQUEST_SERVICE ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_REQUEST_SERVICE', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_REQUEST_SERVICE;
GO
CREATE VIEW dbo.HIS_TT_REQUEST_SERVICE AS
SELECT * FROM (SELECT
  [REQUEST_SERVICE_ID] = CAST(NULL AS INT),
  [REQUEST_ID] = CAST(NULL AS INT),
  [DICHVU_ID] = CAST(NULL AS INT),
  [SOLUONG] = CAST(NULL AS INT),
  [PARA] = CAST(NULL AS NVARCHAR(MAX)),
  [CURR_STATE_CODE] = CAST(NULL AS VARCHAR(50)),
  [PROCESS_CODE] = CAST(NULL AS VARCHAR(50))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_REQUEST_SERVICE_DETAIL ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_REQUEST_SERVICE_DETAIL', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_REQUEST_SERVICE_DETAIL;
GO
CREATE VIEW dbo.HIS_TT_REQUEST_SERVICE_DETAIL AS
SELECT * FROM (SELECT
  [REQUEST_SERVICE_DETAIL_ID] = CAST(NULL AS INT),
  [REQUEST_ID] = CAST(NULL AS INT),
  [REQUEST_SERVICE_ID] = CAST(NULL AS INT),
  [OLD_STATE_CODE] = CAST(NULL AS VARCHAR(50)),
  [CURR_STATE_CODE] = CAST(NULL AS VARCHAR(50)),
  [CHITIET] = CAST(NULL AS NVARCHAR(MAX))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_REQUEST_SERVICE_HISTORY ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_REQUEST_SERVICE_HISTORY', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_REQUEST_SERVICE_HISTORY;
GO
CREATE VIEW dbo.HIS_TT_REQUEST_SERVICE_HISTORY AS
SELECT * FROM (SELECT
  [REQUEST_SERVICE_HISTORY_ID] = CAST(NULL AS INT),
  [REQUEST_ID] = CAST(NULL AS INT),
  [REQUEST_SERVICE_ID] = CAST(NULL AS INT),
  [OLD_STATE_CODE] = CAST(NULL AS VARCHAR(50)),
  [CURR_STATE_CODE] = CAST(NULL AS VARCHAR(50)),
  [THOIGIAN] = CAST(NULL AS DATETIME),
  [NOIDUNG] = CAST(NULL AS NVARCHAR(MAX))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_XACNHANCHIPHI ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_XACNHANCHIPHI', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_XACNHANCHIPHI;
GO
CREATE VIEW dbo.HIS_TT_XACNHANCHIPHI AS
SELECT * FROM (SELECT
  [XACNHANCHIPHI_ID] = CAST(NULL AS INT),
  [TIEPNHAN_ID] = CAST(NULL AS INT),
  [BENHNHAN_ID] = CAST(NULL AS INT),
  [THANHTIEN] = CAST(NULL AS DECIMAL(18,2)),
  [NGAYXACNHAN] = CAST(NULL AS DATETIME)
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TM_DOITUONG ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TM_DOITUONG', 'V') IS NOT NULL DROP VIEW dbo.HIS_TM_DOITUONG;
GO
CREATE VIEW dbo.HIS_TM_DOITUONG AS
SELECT * FROM (SELECT
  [DOITUONG_ID] = CAST(NULL AS INT),
  [DoiTuongUuTien_Id] = CAST(NULL AS INT),
  [Ma] = CAST(NULL AS VARCHAR(20)),
  [TenDoiTuong] = CAST(NULL AS NVARCHAR(200)),
  [TYLE_BHYT] = CAST(NULL AS DECIMAL(4,3))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TM_PHONGBAN ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TM_PHONGBAN', 'V') IS NOT NULL DROP VIEW dbo.HIS_TM_PHONGBAN;
GO
CREATE VIEW dbo.HIS_TM_PHONGBAN AS
SELECT * FROM (SELECT
  [PHONGBAN_ID] = CAST(NULL AS INT),
  [HangDoi_Id] = CAST(NULL AS INT),
  [HangDoiPhongBan_Id] = CAST(NULL AS INT),
  [TenHangDoi] = CAST(NULL AS NVARCHAR(250)),
  [TenPhongBan] = CAST(NULL AS NVARCHAR(200)),
  [TenPhongBanDayDu] = CAST(NULL AS NVARCHAR(250)),
  [Idx] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [TamNgung] = CAST(NULL AS INT),
  [Sound_Id_PhongBan] = CAST(NULL AS INT),
  [LoaiPhongBan] = CAST(NULL AS INT),
  [MaPhongBan] = CAST(NULL AS VARCHAR(50))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_LST_KEYDATA ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_LST_KEYDATA', 'V') IS NOT NULL DROP VIEW dbo.HIS_LST_KEYDATA;
GO
CREATE VIEW dbo.HIS_LST_KEYDATA AS
SELECT * FROM (SELECT
  [KeyData_Id] = CAST(NULL AS INT),
  [Key_Name] = CAST(NULL AS NVARCHAR(100)),
  [Value_Data] = CAST(NULL AS NVARCHAR(MAX)),
  [KEYTYPE] = CAST(NULL AS VARCHAR(50)),
  [KEYYEAR] = CAST(NULL AS INT),
  [KEYMONTH] = CAST(NULL AS VARCHAR(2)),
  [KEYDAY] = CAST(NULL AS VARCHAR(2)),
  [KEYVALUE] = CAST(NULL AS INT),
  [BENHVIEN_ID] = CAST(NULL AS VARCHAR(10)),
  [SEGMENT_1] = CAST(NULL AS VARCHAR(20)),
  [SEGMENT_2] = CAST(NULL AS VARCHAR(20)),
  [SEGMENT_3] = CAST(NULL AS VARCHAR(20)),
  [SEGMENT_4] = CAST(NULL AS VARCHAR(20))
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_CLSYEUCAUCHITIET ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_CLSYEUCAUCHITIET', 'V') IS NOT NULL DROP VIEW dbo.HIS_CLSYEUCAUCHITIET;
GO
CREATE VIEW dbo.HIS_CLSYEUCAUCHITIET AS
SELECT * FROM (SELECT
  [CLSYEUCAUCHITIET_ID] = CAST(NULL AS INT),
  [CLSYeuCau_Id] = CAST(NULL AS INT),
  [DichVu_Id] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [HangDoiPhongBan_Id] = CAST(NULL AS INT),
  [TenBenhNhan] = CAST(NULL AS NVARCHAR(250)),
  [Tuoi] = CAST(NULL AS INT),
  [YeuCauChiTiet_Id] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_CLSYeuCauChiTiet ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_CLSYeuCauChiTiet', 'V') IS NOT NULL DROP VIEW dbo.HIS_CLSYeuCauChiTiet;
GO
CREATE VIEW dbo.HIS_CLSYeuCauChiTiet AS
SELECT * FROM (SELECT
  [CLSYEUCAUCHITIET_ID] = CAST(NULL AS INT),
  [CLSYeuCau_Id] = CAST(NULL AS INT),
  [DichVu_Id] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [HangDoiPhongBan_Id] = CAST(NULL AS INT),
  [TenBenhNhan] = CAST(NULL AS NVARCHAR(250)),
  [Tuoi] = CAST(NULL AS INT),
  [YeuCauChiTiet_Id] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TT_NOITRU_BENHAN ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TT_NOITRU_BENHAN', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_NOITRU_BENHAN;
GO
CREATE VIEW dbo.HIS_TT_NOITRU_BENHAN AS
SELECT * FROM (SELECT
  [BENHAN_ID] = CAST(NULL AS INT),
  [BENHNHAN_ID] = CAST(NULL AS INT),
  [TIEPNHAN_ID] = CAST(NULL AS INT),
  [LOAIBENHAN_ID] = CAST(NULL AS INT),
  [TRANGTHAI] = CAST(NULL AS VARCHAR(20)),
  [KHOABENHAN] = CAST(NULL AS INT),
  [NGAYKHOABENHAN] = CAST(NULL AS DATETIME),
  [NGAYCAPNHAT] = CAST(NULL AS DATETIME),
  [NGUOICAPNHAT_ID] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: HIS_TM_DICHVU_DONGIA ──────────────────────────────────────
IF OBJECT_ID('dbo.HIS_TM_DICHVU_DONGIA', 'V') IS NOT NULL DROP VIEW dbo.HIS_TM_DICHVU_DONGIA;
GO
CREATE VIEW dbo.HIS_TM_DICHVU_DONGIA AS
SELECT * FROM (SELECT
  [DONGIA_ID] = CAST(NULL AS INT),
  [DICHVU_ID] = CAST(NULL AS INT),
  [LOAIGIA_ID] = CAST(NULL AS INT),
  [DONGIA] = CAST(NULL AS DECIMAL(18,2)),
  [TAMNGUNG] = CAST(NULL AS CHAR(1))
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_TiepNhan ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_TiepNhan', 'V') IS NOT NULL DROP VIEW dbo.EHOS_TiepNhan;
GO
CREATE VIEW dbo.EHOS_TiepNhan AS
SELECT * FROM (SELECT
  [TiepNhan_Id] = CAST(NULL AS INT),
  [TiepNhan_ID_New] = CAST(NULL AS INT),
  [TiepNhan_ID_Old] = CAST(NULL AS INT),
  [BenhNhan_Id] = CAST(NULL AS INT),
  [DoiTuong_Id] = CAST(NULL AS INT),
  [PhongBan_Id] = CAST(NULL AS INT),
  [HangDoi_Id] = CAST(NULL AS INT),
  [HangDoiPhongBan_Id] = CAST(NULL AS INT),
  [CLSYeuCau_Id] = CAST(NULL AS INT),
  [QuayTiepNhan_Id] = CAST(NULL AS INT),
  [STT] = CAST(NULL AS INT),
  [STTTheoLoaiPhongBan] = CAST(NULL AS INT),
  [NgayTiepNhan] = CAST(NULL AS DATETIME),
  [NgayThucHien] = CAST(NULL AS DATETIME),
  [NgayGioLaySo] = CAST(NULL AS DATETIME),
  [NgayGioThucHien] = CAST(NULL AS DATETIME),
  [TinhTrang] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [TamNgung] = CAST(NULL AS INT),
  [UuTien] = CAST(NULL AS INT),
  [User_Id] = CAST(NULL AS INT),
  [InKyTuDau] = CAST(NULL AS NVARCHAR(50)),
  [NoiTiepNhan_Id] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_DM_BenhNhan ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_DM_BenhNhan', 'V') IS NOT NULL DROP VIEW dbo.EHOS_DM_BenhNhan;
GO
CREATE VIEW dbo.EHOS_DM_BenhNhan AS
SELECT * FROM (SELECT
  [BenhNhan_Id] = CAST(NULL AS INT),
  [TenBenhNhan] = CAST(NULL AS NVARCHAR(250)),
  [NgaySinh] = CAST(NULL AS DATETIME),
  [NamSinh] = CAST(NULL AS INT),
  [GioiTinh] = CAST(NULL AS VARCHAR(10)),
  [CMND] = CAST(NULL AS VARCHAR(20)),
  [DiaChi] = CAST(NULL AS NVARCHAR(300)),
  [SoDienThoai] = CAST(NULL AS NVARCHAR(50)),
  [SoDienThoaiThanNhan] = CAST(NULL AS NVARCHAR(50)),
  [SoVaoVien] = CAST(NULL AS VARCHAR(50)),
  [MaYTe] = CAST(NULL AS NVARCHAR(50)),
  [MACHUNGTU] = CAST(NULL AS VARCHAR(50)),
  [TiepNhan_Id] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_CLSYeuCau ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_CLSYeuCau', 'V') IS NOT NULL DROP VIEW dbo.EHOS_CLSYeuCau;
GO
CREATE VIEW dbo.EHOS_CLSYeuCau AS
SELECT * FROM (SELECT
  [CLSYeuCau_Id] = CAST(NULL AS INT),
  [DVYEUCAU_ID] = CAST(NULL AS INT),
  [BenhNhan_Id] = CAST(NULL AS INT),
  [BenhAn_Id] = CAST(NULL AS INT),
  [TiepNhan_Id] = CAST(NULL AS INT),
  [DichVu_Id] = CAST(NULL AS INT),
  [NhomDichVu_Id] = CAST(NULL AS INT),
  [DoiTuong_Id] = CAST(NULL AS INT),
  [NoiThucHien_Id] = CAST(NULL AS INT),
  [NoiThucHienThayDoi_Id] = CAST(NULL AS INT),
  [NoiYeuCau_Id] = CAST(NULL AS INT),
  [HuyYeuCau] = CAST(NULL AS CHAR(1)),
  [SODICHVUYEUCAU] = CAST(NULL AS INT),
  [SoPhieuYeuCau] = CAST(NULL AS VARCHAR(50)),
  [NGAYGIOYEUCAU] = CAST(NULL AS DATETIME),
  [NgayYeuCau] = CAST(NULL AS DATETIME),
  [TrangThai] = CAST(NULL AS VARCHAR(50)),
  [Loai] = CAST(NULL AS VARCHAR(20)),
  [NoiDungChiTiet] = CAST(NULL AS NVARCHAR(MAX))
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_CLSYeuCauChiTiet ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_CLSYeuCauChiTiet', 'V') IS NOT NULL DROP VIEW dbo.EHOS_CLSYeuCauChiTiet;
GO
CREATE VIEW dbo.EHOS_CLSYeuCauChiTiet AS
SELECT * FROM (SELECT
  [CLSYEUCAUCHITIET_ID] = CAST(NULL AS INT),
  [CLSYeuCau_Id] = CAST(NULL AS INT),
  [DichVu_Id] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [HangDoiPhongBan_Id] = CAST(NULL AS INT),
  [TenBenhNhan] = CAST(NULL AS NVARCHAR(250)),
  [Tuoi] = CAST(NULL AS INT),
  [YeuCauChiTiet_Id] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_DM_DichVu ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_DM_DichVu', 'V') IS NOT NULL DROP VIEW dbo.EHOS_DM_DichVu;
GO
CREATE VIEW dbo.EHOS_DM_DichVu AS
SELECT * FROM (SELECT
  [DichVu_Id] = CAST(NULL AS INT),
  [TenDichVu] = CAST(NULL AS NVARCHAR(500)),
  [MaDichVu] = CAST(NULL AS VARCHAR(50)),
  [NhomDichVu_Id] = CAST(NULL AS INT)
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_DM_NhomDichVu ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_DM_NhomDichVu', 'V') IS NOT NULL DROP VIEW dbo.EHOS_DM_NhomDichVu;
GO
CREATE VIEW dbo.EHOS_DM_NhomDichVu AS
SELECT * FROM (SELECT
  [NhomDichVu_Id] = CAST(NULL AS INT),
  [CapTren_Id] = CAST(NULL AS INT),
  [TenNhomDichVu] = CAST(NULL AS NVARCHAR(400))
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_DM_PhongBan ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_DM_PhongBan', 'V') IS NOT NULL DROP VIEW dbo.EHOS_DM_PhongBan;
GO
CREATE VIEW dbo.EHOS_DM_PhongBan AS
SELECT * FROM (SELECT
  [PhongBan_Id] = CAST(NULL AS INT),
  [TenPhongBan] = CAST(NULL AS NVARCHAR(200)),
  [TenPhongBanDayDu] = CAST(NULL AS NVARCHAR(250)),
  [LoaiPhongBan_Id] = CAST(NULL AS INT),
  [TamNgung] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [MaPhongBan] = CAST(NULL AS VARCHAR(50))
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_Dm_PhongBan ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_Dm_PhongBan', 'V') IS NOT NULL DROP VIEW dbo.EHOS_Dm_PhongBan;
GO
CREATE VIEW dbo.EHOS_Dm_PhongBan AS
SELECT * FROM (SELECT
  [PhongBan_Id] = CAST(NULL AS INT),
  [TenPhongBan] = CAST(NULL AS NVARCHAR(200)),
  [TenPhongBanDayDu] = CAST(NULL AS NVARCHAR(250)),
  [LoaiPhongBan_Id] = CAST(NULL AS INT),
  [TamNgung] = CAST(NULL AS INT),
  [Huy] = CAST(NULL AS INT),
  [MaPhongBan] = CAST(NULL AS VARCHAR(50))
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_Lst_Dictionary ──────────────────────────────────────
IF OBJECT_ID('dbo.EHOS_Lst_Dictionary', 'V') IS NOT NULL DROP VIEW dbo.EHOS_Lst_Dictionary;
GO
CREATE VIEW dbo.EHOS_Lst_Dictionary AS
SELECT * FROM (SELECT
  [Dictionary_Id] = CAST(NULL AS INT),
  [Code] = CAST(NULL AS VARCHAR(50)),
  [Name] = CAST(NULL AS NVARCHAR(MAX))
) X WHERE 1 = 0;
GO

-- ─── stub: EHOS_GetTenGioiTinh (scalar function) ────────────────
IF OBJECT_ID('dbo.EHOS_GetTenGioiTinh', 'FN') IS NOT NULL DROP FUNCTION dbo.EHOS_GetTenGioiTinh;
GO
CREATE FUNCTION dbo.EHOS_GetTenGioiTinh(@lang VARCHAR(10), @gt VARCHAR(10))
RETURNS NVARCHAR(50)
AS
BEGIN
    RETURN CASE WHEN @gt IN ('T','M','1') THEN N'Nam' WHEN @gt IN ('G','F','0') THEN N'Nữ' ELSE N'' END;
END;
GO

-- ─── stub: HIS_TT_DUOC_CHUNGTU (chứng từ dược — nhánh quét đơn thuốc ở Viện phí) ───
IF OBJECT_ID('dbo.HIS_TT_DUOC_CHUNGTU', 'V') IS NOT NULL DROP VIEW dbo.HIS_TT_DUOC_CHUNGTU;
GO
CREATE VIEW dbo.HIS_TT_DUOC_CHUNGTU AS
SELECT * FROM (SELECT
  [CHUNGTU_ID] = CAST(NULL AS INT),
  [MACHUNGTU] = CAST(NULL AS VARCHAR(50)),
  [BENHNHAN_ID] = CAST(NULL AS INT),
  [TENBENHNHAN] = CAST(NULL AS NVARCHAR(250)),
  [NAMSINH] = CAST(NULL AS INT),
  [MAYTE] = CAST(NULL AS NVARCHAR(50))
) X WHERE 1 = 0;
GO

PRINT 'OK: 99_stub_views.sql applied';
GO
