# start-demo.ps1 - Start the QMS demo and auto-configure the LAN IP for QR scanning.
# Run this at ANY venue: it detects the current Wi-Fi/LAN IP, writes it into
# frontend/.env.local so the Kiosk QR points to a phone-reachable URL, then
# starts backend + frontend. Phone must be on the SAME wifi/LAN.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# 1) Detect LAN IPv4 (prefer Wi-Fi, then Ethernet; skip loopback/APIPA/virtual)
$cands = Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.PrefixOrigin -ne 'WellKnown' }
$pick = $cands | Sort-Object @{ Expression = {
    if ($_.InterfaceAlias -match 'Wi-?Fi|Wireless|WLAN') { 0 }
    elseif ($_.InterfaceAlias -match 'Ethernet|LAN') { 1 } else { 2 } } } |
  Select-Object -First 1
if (-not $pick) { Write-Host "No LAN IP found. Check your wifi connection." -ForegroundColor Red; exit 1 }
$ip = $pick.IPAddress
$base = "http://$($ip):5173"

# 2) Write .env.local so the Kiosk QR uses this IP
$envFile = Join-Path $root 'frontend\.env.local'
@"
# AUTO-generated by start-demo.ps1 - do not commit. IP changes per wifi.
VITE_PUBLIC_URL=$base
"@ | Set-Content -Path $envFile -Encoding utf8
Write-Host "==> LAN IP : $ip ($($pick.InterfaceAlias))" -ForegroundColor Green
Write-Host "==> Kiosk QR will point to: $base/track?id=..." -ForegroundColor Green

# 3) Open firewall port 5173 (needs admin once; skipped otherwise)
try {
  if (-not (Get-NetFirewallRule -DisplayName 'QMS Vite 5173' -ErrorAction SilentlyContinue)) {
    New-NetFirewallRule -DisplayName 'QMS Vite 5173' -Direction Inbound -LocalPort 5173 -Protocol TCP -Action Allow -Profile Any -ErrorAction Stop | Out-Null
    Write-Host "==> Firewall rule for 5173 added." -ForegroundColor Green
  } else { Write-Host "==> Firewall rule for 5173 already present." -ForegroundColor Green }
} catch {
  Write-Host "!! Could not add firewall rule (run PowerShell as Administrator once):" -ForegroundColor Yellow
  Write-Host '   New-NetFirewallRule -DisplayName "QMS Vite 5173" -Direction Inbound -LocalPort 5173 -Protocol TCP -Action Allow' -ForegroundColor Yellow
}

# 4) Start backend (if down) + frontend
$beUp = Get-NetTCPConnection -State Listen -LocalPort 5000 -ErrorAction SilentlyContinue
if (-not $beUp) {
  Write-Host "==> Starting backend :5000 ..." -ForegroundColor Cyan
  Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$root'; dotnet run --project backend/Qms.API --urls http://localhost:5000"
}
Write-Host "==> Starting frontend :5173 ..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$root\frontend'; npm run dev"

Write-Host ""
Write-Host "DONE. Open the kiosk at:  $base/kiosk/tiep-nhan  -> take a number -> QR points to this IP." -ForegroundColor Green
Write-Host "Scan the QR with a phone on the SAME wifi to track." -ForegroundColor Green
