"""
clone_data.py — Script clone data từ source DB về local QMS_DA.

- KHÔNG dùng linked server.
- Đọc từ source DB qua env SRC_DB_SERVER bằng pyodbc.
- INSERT vào QMS_DA (localhost\\SQLEXPRESS) trực tiếp + generate file SQL
  idempotent vào ../20-27_seed_*.sql cho future reproduce.

Idempotent: `IF NOT EXISTS (SELECT 1 FROM dst WHERE pk=...) INSERT ...`
Anonymize: CMND -> 'xxx***', SDT -> 'yyy****zz'.
"""
from __future__ import annotations

import io
import os
import sys
from datetime import datetime
from typing import Any, Iterable, Sequence

import pyodbc

# ─── Setup encoding ───
sys.stdout.reconfigure(encoding="utf-8")

# ─── Connection strings (đọc từ env — KHÔNG hardcode credential) ───
# Set env trước khi chạy:
#   $env:SRC_DB_SERVER = "103.161.112.56,1433"
#   $env:SRC_DB_USER   = "your_user"
#   $env:SRC_DB_PASS   = "your_password"
_SRC_SRV = os.environ.get("SRC_DB_SERVER", "")
_SRC_USR = os.environ.get("SRC_DB_USER", "")
_SRC_PWD = os.environ.get("SRC_DB_PASS", "")

SRC_QMS_CS = (
    f"Driver={{ODBC Driver 17 for SQL Server}};Server={_SRC_SRV};"
    f"Database=K_QMS_YHCT;UID={_SRC_USR};PWD={_SRC_PWD};TrustServerCertificate=yes"
)
SRC_HIS_CS = (
    f"Driver={{ODBC Driver 17 for SQL Server}};Server={_SRC_SRV};"
    f"Database=PRODUCT_HIS;UID={_SRC_USR};PWD={_SRC_PWD};TrustServerCertificate=yes"
)
DST_CS = os.environ.get(
    "DST_DB_CS",
    "Driver={ODBC Driver 17 for SQL Server};Server=localhost\\SQLEXPRESS;"
    "Database=QMS_DA;Trusted_Connection=yes;TrustServerCertificate=yes",
)

# ─── Output dir for generated SQL files ───
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.abspath(os.path.join(HERE, ".."))


# ═══════════════════════════════════════════════════════════════════
# SQL helpers
# ═══════════════════════════════════════════════════════════════════

def sql_literal(v: Any) -> str:
    """Convert a Python value to a T-SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, datetime):
        return "'" + v.strftime("%Y-%m-%d %H:%M:%S") + "'"
    # string
    s = str(v).replace("'", "''")
    return "N'" + s + "'"


def anonymize_cmnd(s: str | None) -> str | None:
    if not s:
        return s
    s = str(s).strip()
    if len(s) <= 3:
        return s
    return s[:-3] + "***"


def anonymize_phone(s: str | None) -> str | None:
    if not s:
        return s
    s = str(s).strip()
    if len(s) < 10:
        return s
    # 0901123456 -> 0901****56  (replace 4 middle chars at position 4..8)
    return s[:4] + "****" + s[8:]


# ═══════════════════════════════════════════════════════════════════
# Generic file writer
# ═══════════════════════════════════════════════════════════════════

class SqlFile:
    """Builds an idempotent SQL seed file."""
    def __init__(self, filename: str, title: str):
        self.path = os.path.join(OUT_DIR, filename)
        self.buf = io.StringIO()
        self.buf.write("-- " + "═" * 64 + "\n")
        self.buf.write(f"-- {filename}\n")
        self.buf.write(f"-- {title}\n")
        self.buf.write(f"-- Auto-generated by _scripts/clone_data.py at {datetime.now().isoformat(timespec='seconds')}.\n")
        self.buf.write("-- Idempotent: chạy lại nhiều lần OK (skip nếu row đã tồn tại).\n")
        self.buf.write("-- " + "═" * 64 + "\n\n")
        self.buf.write("SET QUOTED_IDENTIFIER ON;\nSET ANSI_NULLS ON;\nGO\nUSE QMS_DA;\nGO\n\n")

    def section(self, title: str) -> None:
        self.buf.write(f"-- ─── {title} ─── \n")

    def write(self, sql: str) -> None:
        self.buf.write(sql)
        if not sql.endswith("\n"):
            self.buf.write("\n")

    def save(self) -> None:
        self.buf.write("\nPRINT 'OK: " + os.path.basename(self.path) + "';\nGO\n")
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(self.buf.getvalue())
        print(f"  > wrote {os.path.relpath(self.path, OUT_DIR)}")


# ═══════════════════════════════════════════════════════════════════
# Connection cache
# ═══════════════════════════════════════════════════════════════════

_conns: dict[str, pyodbc.Connection] = {}


def conn(cs: str) -> pyodbc.Connection:
    if cs not in _conns:
        _conns[cs] = pyodbc.connect(cs, timeout=20)
    return _conns[cs]


def src_qms() -> pyodbc.Connection:
    return conn(SRC_QMS_CS)


def src_his() -> pyodbc.Connection:
    return conn(SRC_HIS_CS)


def dst() -> pyodbc.Connection:
    if DST_CS not in _conns:
        c = pyodbc.connect(DST_CS, timeout=20, autocommit=True)
        _conns[DST_CS] = c
    return _conns[DST_CS]


# ═══════════════════════════════════════════════════════════════════
# Generic clone helper
# ═══════════════════════════════════════════════════════════════════

def clone_table(
    src_conn: pyodbc.Connection,
    src_query: str,
    dst_table: str,
    pk_col: str,
    columns: Sequence[str],
    identity_insert: bool,
    sql_file: SqlFile,
    section_title: str,
    transform=None,
) -> int:
    """
    Generic clone:
      - SELECT rows from src
      - For each row: emit idempotent INSERT to QMS_DA + apply transform
    Returns number of rows actually inserted.
    """
    sql_file.section(section_title)
    cur = src_conn.cursor()
    cur.execute(src_query)
    rows = cur.fetchall()
    print(f"  source: {len(rows)} rows from `{section_title}`")

    if identity_insert:
        sql_file.write(f"SET IDENTITY_INSERT dbo.{dst_table} ON;")
        # Run via dst() too
        dst().execute(f"SET IDENTITY_INSERT dbo.{dst_table} ON;")

    inserted = 0
    skipped = 0
    for r in rows:
        rec = dict(zip(columns, r))
        if transform is not None:
            rec = transform(rec)
            if rec is None:
                continue
        pk_val = rec[pk_col]
        # Build INSERT
        cols_sql = ", ".join(columns)
        vals_sql = ", ".join(sql_literal(rec[c]) for c in columns)
        guard = (
            f"IF NOT EXISTS (SELECT 1 FROM dbo.{dst_table} WHERE {pk_col} = {sql_literal(pk_val)})\n"
            f"  INSERT INTO dbo.{dst_table} ({cols_sql}) VALUES ({vals_sql});"
        )
        sql_file.write(guard)
        # Apply to live DB
        try:
            check = dst().cursor().execute(
                f"SELECT 1 FROM dbo.{dst_table} WHERE {pk_col} = ?", pk_val
            ).fetchone()
            if check:
                skipped += 1
                continue
            placeholders = ", ".join("?" for _ in columns)
            dst().cursor().execute(
                f"INSERT INTO dbo.{dst_table} ({cols_sql}) VALUES ({placeholders})",
                *(rec[c] for c in columns),
            )
            inserted += 1
        except Exception as e:
            print(f"    ! row pk={pk_val} ERROR: {e}")
            sql_file.write(f"-- WARNING: row pk={pk_val} failed locally: {e}")

    if identity_insert:
        sql_file.write(f"SET IDENTITY_INSERT dbo.{dst_table} OFF;\nGO")
        dst().execute(f"SET IDENTITY_INSERT dbo.{dst_table} OFF;")

    sql_file.write("")
    print(f"    inserted={inserted}  skipped(exists)={skipped}")
    return inserted


# ═══════════════════════════════════════════════════════════════════
# 3.1 — Clone 200 BN + BHYT
# ═══════════════════════════════════════════════════════════════════

def clone_benhnhan() -> tuple[int, int]:
    """Returns (n_bn, n_bhyt)."""
    print("\n[3.1] Clone 200 BN + BHYT records")
    sql_file = SqlFile(
        "20_seed_benhnhan.sql",
        "Seed dbo.BenhNhan + dbo.BenhNhan_BHYT (200 BN, anonymized).",
    )

    # 1) Lấy top 200 BN ID — ưu tiên BN có BHYT
    cur = src_his().cursor()
    cur.execute(
        """
        SELECT TOP 200 bn.BENHNHAN_ID
        FROM PRODUCT_HIS.dbo.TT_BENHNHAN bn
        LEFT JOIN PRODUCT_HIS.dbo.TT_BENHNHAN_BHYT bh ON bn.BENHNHAN_ID = bh.BENHNHAN_ID
        WHERE bn.MAYTE IS NOT NULL AND LEN(bn.MAYTE) > 0
          AND bn.TENBENHNHAN IS NOT NULL
        ORDER BY (CASE WHEN bh.SOTHE IS NOT NULL THEN 0 ELSE 1 END),
                 bn.BENHNHAN_ID DESC
        """
    )
    bn_ids = [r[0] for r in cur.fetchall()]
    print(f"  selected {len(bn_ids)} BN ids")

    if not bn_ids:
        print("  ! no BN found — abort")
        return (0, 0)

    # 2) Load BN records (chỉ cột mình cần)
    bn_cols = (
        "BENHNHAN_ID, MAYTE, SOVAOVIEN, TENBENHNHAN, HO, TEN, GIOITINH, "
        "NGAYSINH, NAMSINH, SODIENTHOAI, DIACHI, DIACHITHUONGTRU, CMND, EMAIL, "
        "ACTIVE, NGAYTAO, NGUOITAO_ID, NGAYCAPNHAT, NGUOICAPNHAT_ID"
    )
    placeholders = ",".join(str(x) for x in bn_ids)
    cur.execute(
        f"SELECT {bn_cols} FROM PRODUCT_HIS.dbo.TT_BENHNHAN WHERE BENHNHAN_ID IN ({placeholders})"
    )
    bn_rows = cur.fetchall()
    bn_col_list = tuple(c.strip() for c in bn_cols.split(","))

    def bn_transform(rec: dict[str, Any]) -> dict[str, Any]:
        rec["CMND"] = anonymize_cmnd(rec.get("CMND"))
        rec["SODIENTHOAI"] = anonymize_phone(rec.get("SODIENTHOAI"))
        # ACTIVE default '1' nếu NULL
        if rec.get("ACTIVE") is None:
            rec["ACTIVE"] = "1"
        return rec

    sql_file.section("BenhNhan (200 rows)")
    n_bn = 0
    skipped_bn = 0
    sql_file.write("SET IDENTITY_INSERT dbo.BenhNhan OFF;  -- BENHNHAN_ID là NOT IDENTITY, không cần\n")
    for r in bn_rows:
        rec = dict(zip(bn_col_list, r))
        rec = bn_transform(rec)
        bn_id = rec["BENHNHAN_ID"]
        cols_sql = ", ".join(bn_col_list)
        vals_sql = ", ".join(sql_literal(rec[c]) for c in bn_col_list)
        sql_file.write(
            f"IF NOT EXISTS (SELECT 1 FROM dbo.BenhNhan WHERE BENHNHAN_ID = {bn_id})\n"
            f"  INSERT INTO dbo.BenhNhan ({cols_sql}) VALUES ({vals_sql});"
        )
        # apply
        try:
            check = dst().cursor().execute(
                "SELECT 1 FROM dbo.BenhNhan WHERE BENHNHAN_ID = ?", bn_id
            ).fetchone()
            if check:
                skipped_bn += 1
                continue
            ph = ", ".join("?" for _ in bn_col_list)
            dst().cursor().execute(
                f"INSERT INTO dbo.BenhNhan ({cols_sql}) VALUES ({ph})",
                *(rec[c] for c in bn_col_list),
            )
            n_bn += 1
        except Exception as e:
            print(f"    ! BN {bn_id} ERROR: {e}")
            sql_file.write(f"-- WARNING: BN {bn_id} failed: {e}")
    sql_file.write("")
    print(f"  BenhNhan inserted={n_bn} skipped={skipped_bn}")

    # 3) BHYT cho 200 BN
    bhyt_cols = (
        "BENHNHAN_BHYT_ID, BENHNHAN_ID, LOAIBHYT, SOTHE, NGAYCAP, NGAYHIEULUC, "
        "NGAYHETHIEULUC, TREN6THANG, TREN3NAM, TREN5NAM, NGAYMIENDONGCHITRA, "
        "KHUVUCSONG_ID, BENHVIEN_KCB_ID, TAMNGUNG, NGAYTAO, NGAYCAPNHAT"
    )
    cur.execute(
        f"SELECT {bhyt_cols} FROM PRODUCT_HIS.dbo.TT_BENHNHAN_BHYT "
        f"WHERE BENHNHAN_ID IN ({placeholders})"
    )
    bhyt_rows = cur.fetchall()
    bhyt_col_list = tuple(c.strip() for c in bhyt_cols.split(","))

    sql_file.section(f"BenhNhan_BHYT ({len(bhyt_rows)} rows) — IDENTITY_INSERT ON")
    sql_file.write("SET IDENTITY_INSERT dbo.BenhNhan_BHYT ON;")
    dst().execute("SET IDENTITY_INSERT dbo.BenhNhan_BHYT ON;")

    n_bhyt = 0
    skipped_bhyt = 0
    for r in bhyt_rows:
        rec = dict(zip(bhyt_col_list, r))
        bh_id = rec["BENHNHAN_BHYT_ID"]
        cols_sql = ", ".join(bhyt_col_list)
        vals_sql = ", ".join(sql_literal(rec[c]) for c in bhyt_col_list)
        sql_file.write(
            f"IF NOT EXISTS (SELECT 1 FROM dbo.BenhNhan_BHYT WHERE BENHNHAN_BHYT_ID = {bh_id})\n"
            f"  INSERT INTO dbo.BenhNhan_BHYT ({cols_sql}) VALUES ({vals_sql});"
        )
        try:
            check = dst().cursor().execute(
                "SELECT 1 FROM dbo.BenhNhan_BHYT WHERE BENHNHAN_BHYT_ID = ?", bh_id
            ).fetchone()
            if check:
                skipped_bhyt += 1
                continue
            ph = ", ".join("?" for _ in bhyt_col_list)
            dst().cursor().execute(
                f"INSERT INTO dbo.BenhNhan_BHYT ({cols_sql}) VALUES ({ph})",
                *(rec[c] for c in bhyt_col_list),
            )
            n_bhyt += 1
        except Exception as e:
            print(f"    ! BHYT id={bh_id} ERROR: {e}")
            sql_file.write(f"-- WARNING: BHYT {bh_id} failed: {e}")

    sql_file.write("SET IDENTITY_INSERT dbo.BenhNhan_BHYT OFF;\nGO\n")
    dst().execute("SET IDENTITY_INSERT dbo.BenhNhan_BHYT OFF;")
    sql_file.save()
    print(f"  BenhNhan_BHYT inserted={n_bhyt} skipped={skipped_bhyt}")
    return (n_bn, n_bhyt)


# ═══════════════════════════════════════════════════════════════════
# 3.2 — Catalog from K_QMS_YHCT
# ═══════════════════════════════════════════════════════════════════

def clone_dm_hangdoi() -> int:
    print("\n[3.2a] Clone DM_HangDoi")
    sf = SqlFile("21_seed_dm_hangdoi.sql", "Seed dbo.DM_HangDoi.")
    cols = (
        "HangDoi_Id", "MaHangDoi", "TenHangDoi", "KyTuSTT", "TamNgung",
        "NgayTao", "NguoiTao", "NgayCapNhat", "NguoiCapNhat", "Huy",
        "Sound_Id_KyTu", "PhongBanEhospital_Id",
    )
    n = clone_table(
        src_qms(),
        f"SELECT {', '.join(cols)} FROM dbo.DM_HangDoi ORDER BY HangDoi_Id",
        "DM_HangDoi", "HangDoi_Id", cols, identity_insert=True,
        sql_file=sf, section_title="DM_HangDoi",
    )
    sf.save()
    return n


def clone_dm_phongban() -> int:
    print("\n[3.2b] Clone DM_PhongBan")
    sf = SqlFile("22_seed_dm_phongban.sql", "Seed dbo.DM_PhongBan + dbo.DM_PhongBanLoaiPhongBan.")
    # First LoaiPhongBan (FK target)
    src_q = src_qms().cursor()
    src_q.execute("""
        SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME='DM_PhongBanLoaiPhongBan' ORDER BY ORDINAL_POSITION
    """)
    loai_cols = tuple(r[0] for r in src_q.fetchall())
    if loai_cols:
        # filter only the cols present in QMS_DA schema
        allowed = ("LoaiPhongBan_Id", "TenLoaiPhongBan", "TenLoaiPhongBanDayDu",
                   "STTPhongBan", "TamNgung", "Huy", "NgayTao", "NguoiTao",
                   "NgayCapNhat", "NguoiCapNhat", "MoTa")
        use = tuple(c for c in loai_cols if c in allowed)
        n_loai = clone_table(
            src_qms(),
            f"SELECT {', '.join(use)} FROM dbo.DM_PhongBanLoaiPhongBan",
            "DM_PhongBanLoaiPhongBan", "LoaiPhongBan_Id", use, identity_insert=True,
            sql_file=sf, section_title="DM_PhongBanLoaiPhongBan",
        )
    else:
        n_loai = 0

    cols = (
        "PhongBan_Id", "TenPhongBan", "TenPhongBanDayDu", "PhongBanEhospital_Id",
        "STTPhongBan", "LoaiPhongBan", "TamNgung", "Huy", "NgayTao", "NguoiTao",
        "NgayCapNhat", "NguoiCapNhat", "MoTa", "Sound_Id_PhongBan",
    )
    n_pb = clone_table(
        src_qms(),
        f"SELECT {', '.join(cols)} FROM dbo.DM_PhongBan ORDER BY PhongBan_Id",
        "DM_PhongBan", "PhongBan_Id", cols, identity_insert=True,
        sql_file=sf, section_title="DM_PhongBan",
    )
    sf.save()
    return n_pb + n_loai


def clone_users_menu() -> tuple[int, int, int]:
    """Returns (users, users_phongban, n_menu_perm)"""
    print("\n[3.2c] Clone Sys_Users + Sys_Users_PhongBan")
    sf = SqlFile(
        "23_seed_users.sql",
        "Seed dbo.Sys_Users (password giữ nguyên encrypted blob, plaintext='123') + dbo.Sys_Users_PhongBan.",
    )
    user_cols = (
        "User_Id", "UserCode", "UserName", "Password", "BenhVien_Id", "TamNgung",
        "NguoiTao", "NgayTao", "NguoiCapNhat", "NgayCapNhat", "Huy",
        "MoTaMay", "MoTaKetNoiMay", "MoTaKetNoiTiVi", "MoTaKetNoiAmThanh",
        "TenTivi", "TenAmThanh",
    )
    n_users = clone_table(
        src_qms(),
        f"SELECT {', '.join(user_cols)} FROM dbo.Sys_Users ORDER BY User_Id",
        "Sys_Users", "User_Id", user_cols, identity_insert=True,
        sql_file=sf, section_title="Sys_Users (29 rows, plaintext password='123')",
    )

    upb_cols = ("User_PhongBan_Id", "User_Id", "PhongBan_Id", "HangDoi_Id")
    n_upb = clone_table(
        src_qms(),
        f"SELECT {', '.join(upb_cols)} FROM dbo.Sys_Users_PhongBan",
        "Sys_Users_PhongBan", "User_PhongBan_Id", upb_cols, identity_insert=True,
        sql_file=sf, section_title="Sys_Users_PhongBan",
    )
    sf.save()
    return (n_users, n_upb, 0)


def clone_menu_permission() -> tuple[int, int]:
    print("\n[3.2d] Clone Menu + Permission")
    sf = SqlFile("24_seed_menu.sql", "Seed dbo.Menu + dbo.Permission.")
    menu_cols = (
        "Menu_Id", "MenuCode", "MenuName", "ParentMenu", "TamNgung",
        "NgayTao", "NguoiTao", "NgayCapNhat", "NguoiCapNhat", "Huy",
    )
    n_menu = clone_table(
        src_qms(),
        f"SELECT {', '.join(menu_cols)} FROM dbo.Menu ORDER BY Menu_Id",
        "Menu", "Menu_Id", menu_cols, identity_insert=True,
        sql_file=sf, section_title="Menu",
    )
    perm_cols = ("Permission_Id", "User_Id", "Menu_Id")
    n_perm = clone_table(
        src_qms(),
        f"SELECT {', '.join(perm_cols)} FROM dbo.Permission",
        "Permission", "Permission_Id", perm_cols, identity_insert=True,
        sql_file=sf, section_title="Permission",
    )
    sf.save()
    return (n_menu, n_perm)


def clone_misc() -> tuple[int, int, int]:
    print("\n[3.2e] Clone DM_NoiDungDacBiet + DM_ThoiGianDichVu + K_DM_DoiTuongUuTien")
    sf = SqlFile(
        "25_seed_misc.sql",
        "Seed DM_NoiDungDacBiet + DM_ThoiGianDichVu + K_DM_DoiTuongUuTien.",
    )

    # DM_NoiDungDacBiet (probably empty)
    ndb_cols = (
        "NoiDungDacBiet_Id", "TenNoiDung", "Loai", "PhongBan_Id", "HangDoi_Id",
        "TamNgung", "Huy", "NgayTao", "NguoiTao", "NgayCapNhat", "NguoiCapNhat",
        "IdLienQuan",
    )
    n1 = clone_table(
        src_qms(),
        f"SELECT {', '.join(ndb_cols)} FROM dbo.DM_NoiDungDacBiet",
        "DM_NoiDungDacBiet", "NoiDungDacBiet_Id", ndb_cols, identity_insert=True,
        sql_file=sf, section_title="DM_NoiDungDacBiet",
    )

    # DM_ThoiGianDichVu — KHÔNG seed lúc này (FK ràng buộc DichVu_Id, sẽ seed sau khi
    # DM_DichVu đã có data ở file 26). Để tránh FK violation ta filter only rows
    # whose DichVu_Id IS NULL hoặc nằm trong DM_DichVu sẽ load.
    # Đơn giản: bỏ qua hoàn toàn (DM_DichVu seed 500 thông dụng, không đủ map).
    sf.section("DM_ThoiGianDichVu — SKIPPED (FK constraint to DM_DichVu, seed sau khi 26 chạy nếu cần)")
    sf.write("-- DM_ThoiGianDichVu có 110 rows ở DB cũ. FK -> DM_DichVu. Skip để tránh fail.")
    sf.write("-- Có thể seed thủ công sau khi đã load DM_DichVu top500.\n")
    n_tgdv = 0

    dtut_cols = ("DoiTuongUuTien_Id", "TenDoiTuong", "Huy")
    n3 = clone_table(
        src_qms(),
        f"SELECT {', '.join(dtut_cols)} FROM dbo.K_DM_DoiTuongUuTien ORDER BY DoiTuongUuTien_Id",
        "K_DM_DoiTuongUuTien", "DoiTuongUuTien_Id", dtut_cols, identity_insert=True,
        sql_file=sf, section_title="K_DM_DoiTuongUuTien",
    )

    sf.save()
    return (n1, n_tgdv, n3)


# ═══════════════════════════════════════════════════════════════════
# 3.2 — Service catalog from PRODUCT_HIS
# ═══════════════════════════════════════════════════════════════════

def clone_dichvu_catalog() -> tuple[int, int, int]:
    print("\n[3.2f] Clone TM_LOAIDICHVU + TM_NHOMDICHVU + TM_DICHVU (top 500)")
    sf = SqlFile(
        "26_seed_dichvu_catalog.sql",
        "Seed dbo.DM_LoaiDichVu + dbo.DM_NhomDichVu + dbo.DM_DichVu (top 500 thông dụng).",
    )

    # 1. DM_LoaiDichVu
    cur = src_his().cursor()
    cur.execute("""
        SELECT LOAIDICHVU_ID, MALOAIDICHVU, TENLOAIDICHVU, TENKHONGDAU, TAMNGUNG
        FROM dbo.TM_LOAIDICHVU ORDER BY LOAIDICHVU_ID
    """)
    sf.section("DM_LoaiDichVu")
    n_loai = 0
    for r in cur.fetchall():
        rec = dict(LOAIDICHVU_ID=r[0], MALOAIDICHVU=r[1], TENLOAIDICHVU=r[2],
                   TENKHONGDAU=r[3], TAMNGUNG=r[4])
        cols = ("LOAIDICHVU_ID", "MALOAIDICHVU", "TENLOAIDICHVU", "TENKHONGDAU", "TAMNGUNG")
        vals = ", ".join(sql_literal(rec[c]) for c in cols)
        sf.write(
            f"IF NOT EXISTS (SELECT 1 FROM dbo.DM_LoaiDichVu WHERE LOAIDICHVU_ID = {r[0]})\n"
            f"  INSERT INTO dbo.DM_LoaiDichVu ({', '.join(cols)}) VALUES ({vals});"
        )
        try:
            chk = dst().cursor().execute("SELECT 1 FROM dbo.DM_LoaiDichVu WHERE LOAIDICHVU_ID=?", r[0]).fetchone()
            if chk:
                continue
            dst().cursor().execute(
                f"INSERT INTO dbo.DM_LoaiDichVu ({', '.join(cols)}) VALUES (?,?,?,?,?)",
                *(rec[c] for c in cols),
            )
            n_loai += 1
        except Exception as e:
            print(f"    ! LoaiDV {r[0]} ERROR: {e}")
    print(f"  DM_LoaiDichVu inserted={n_loai}")
    sf.write("")

    # 2. DM_NhomDichVu
    cur.execute("""
        SELECT NHOMDICHVU_ID, MANHOMDICHVU, LOAIDICHVU_ID, TENNHOMDICHVU,
               TENKHONGDAU, CAP, CAPTREN_ID, TAMNGUNG
        FROM dbo.TM_NHOMDICHVU ORDER BY NHOMDICHVU_ID
    """)
    sf.section("DM_NhomDichVu")
    n_nhom = 0
    cols = ("NHOMDICHVU_ID", "MANHOMDICHVU", "LOAIDICHVU_ID", "TENNHOMDICHVU",
            "TENKHONGDAU", "CAP", "CAPTREN_ID", "TAMNGUNG")
    for r in cur.fetchall():
        rec = dict(zip(cols, r))
        vals = ", ".join(sql_literal(rec[c]) for c in cols)
        sf.write(
            f"IF NOT EXISTS (SELECT 1 FROM dbo.DM_NhomDichVu WHERE NHOMDICHVU_ID = {r[0]})\n"
            f"  INSERT INTO dbo.DM_NhomDichVu ({', '.join(cols)}) VALUES ({vals});"
        )
        try:
            chk = dst().cursor().execute("SELECT 1 FROM dbo.DM_NhomDichVu WHERE NHOMDICHVU_ID=?", r[0]).fetchone()
            if chk:
                continue
            dst().cursor().execute(
                f"INSERT INTO dbo.DM_NhomDichVu ({', '.join(cols)}) VALUES (?,?,?,?,?,?,?,?)",
                *(rec[c] for c in cols),
            )
            n_nhom += 1
        except Exception as e:
            print(f"    ! NhomDV {r[0]} ERROR: {e}")
    print(f"  DM_NhomDichVu inserted={n_nhom}")
    sf.write("")

    # 3. DM_DichVu (top 500 thông dụng: TAMNGUNG='0' + ordered by DICHVU_ID)
    cur.execute("""
        SELECT TOP 500 DICHVU_ID, NHOMDICHVU_ID, MADICHVU, TENDICHVU, TENKHONGDAU,
               DONVITINH, CAP, CAPTREN_ID, TAMNGUNG, BHYT, THOIGIANTHUCHIEN
        FROM dbo.TM_DICHVU
        WHERE TAMNGUNG = '0'
        ORDER BY DICHVU_ID
    """)
    sf.section("DM_DichVu (TOP 500 chưa tạm ngưng)")
    n_dv = 0
    cols = ("DICHVU_ID", "NHOMDICHVU_ID", "MADICHVU", "TENDICHVU", "TENKHONGDAU",
            "DONVITINH", "CAP", "CAPTREN_ID", "TAMNGUNG", "BHYT", "THOIGIANTHUCHIEN")
    for r in cur.fetchall():
        rec = dict(zip(cols, r))
        vals = ", ".join(sql_literal(rec[c]) for c in cols)
        sf.write(
            f"IF NOT EXISTS (SELECT 1 FROM dbo.DM_DichVu WHERE DICHVU_ID = {r[0]})\n"
            f"  INSERT INTO dbo.DM_DichVu ({', '.join(cols)}) VALUES ({vals});"
        )
        try:
            chk = dst().cursor().execute("SELECT 1 FROM dbo.DM_DichVu WHERE DICHVU_ID=?", r[0]).fetchone()
            if chk:
                continue
            dst().cursor().execute(
                f"INSERT INTO dbo.DM_DichVu ({', '.join(cols)}) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                *(rec[c] for c in cols),
            )
            n_dv += 1
        except Exception as e:
            print(f"    ! DichVu {r[0]} ERROR: {e}")
    print(f"  DM_DichVu inserted={n_dv}")
    sf.save()
    return (n_loai, n_nhom, n_dv)


# ═══════════════════════════════════════════════════════════════════
# 3.3 — DM_DoiTuong (manual seed)
# ═══════════════════════════════════════════════════════════════════

def seed_dm_doituong() -> int:
    print("\n[3.3] Seed DM_DoiTuong (manual)")
    sf = SqlFile("27_seed_dm_doituong.sql", "Seed dbo.DM_DoiTuong (manual — không có ở DB cũ).")
    sf.section("DM_DoiTuong (6 rows)")
    rows = [
        ("DV",    "Dịch vụ",                   0.000, 0),
        ("BH80",  "BHYT 80%",                  0.800, 0),
        ("BH95",  "BHYT 95%",                  0.950, 0),
        ("BH100", "BHYT 100%",                 1.000, 0),
        ("BH5N",  "BHYT 5 năm (80% -> 100%)",  0.800, 1),
        ("BHCD",  "BHYT chuyển đến",           0.800, 0),
    ]
    n = 0
    for ma, ten, ty, b5 in rows:
        sf.write(
            f"IF NOT EXISTS (SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma = N'{ma}')\n"
            f"  INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) "
            f"VALUES (N'{ma}', N'{ten}', {ty}, {b5});"
        )
        try:
            chk = dst().cursor().execute("SELECT 1 FROM dbo.DM_DoiTuong WHERE Ma=?", ma).fetchone()
            if chk:
                continue
            dst().cursor().execute(
                "INSERT INTO dbo.DM_DoiTuong (Ma, TenDoiTuong, TYLE_BHYT, BHYT_5NAM) VALUES (?,?,?,?)",
                ma, ten, ty, b5,
            )
            n += 1
        except Exception as e:
            print(f"    ! DoiTuong {ma} ERROR: {e}")
    sf.save()
    print(f"  DM_DoiTuong inserted={n}")
    return n


# ═══════════════════════════════════════════════════════════════════
# Verification & smoke test
# ═══════════════════════════════════════════════════════════════════

def verify_counts() -> None:
    print("\n[VERIFY] row counts in QMS_DA")
    cur = dst().cursor()
    tables = [
        "BenhNhan", "BenhNhan_BHYT",
        "DM_HangDoi", "DM_PhongBan", "DM_PhongBanLoaiPhongBan",
        "Sys_Users", "Sys_Users_PhongBan",
        "Menu", "Permission",
        "DM_NoiDungDacBiet", "K_DM_DoiTuongUuTien",
        "DM_LoaiDichVu", "DM_NhomDichVu", "DM_DichVu",
        "DM_DoiTuong",
    ]
    for t in tables:
        try:
            cur.execute(f"SELECT COUNT(*) FROM dbo.{t}")
            n = cur.fetchone()[0]
            print(f"  {t:30s} = {n}")
        except Exception as e:
            print(f"  {t:30s} ERR: {e}")


def smoke_test_sp() -> None:
    print("\n[SMOKE TEST] SP_K_002_HangDoiTiepNhan CheckSoVaoVienVP")
    cur = dst().cursor()
    cur.execute("SELECT TOP 5 BENHNHAN_ID, MAYTE, TENBENHNHAN, NAMSINH FROM dbo.BenhNhan")
    samples = cur.fetchall()
    print("  Sample BN từ DB local:")
    for r in samples:
        print(f"    id={r[0]:>8} maYte={r[1]:>15} ten={r[2]:<40} namSinh={r[3]}")

    # Test 2: lookup BHYT
    cur.execute("""
        SELECT TOP 3 bn.BENHNHAN_ID, bn.MAYTE, bn.TENBENHNHAN, bh.SOTHE, bh.LOAIBHYT
        FROM dbo.BenhNhan bn
        INNER JOIN dbo.BenhNhan_BHYT bh ON bn.BENHNHAN_ID = bh.BENHNHAN_ID
    """)
    rows = cur.fetchall()
    print(f"  BN có BHYT ({len(rows)} sample):")
    for r in rows:
        print(f"    id={r[0]} maYte={r[1]} ten={r[2]:<40} soThe={r[3]}")


# ═══════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════

def main() -> int:
    print(f"clone_data.py — Pha 3 seed @ {datetime.now().isoformat(timespec='seconds')}")
    print(f"  source: {_SRC_SRV or '<SRC_DB_SERVER not set>'}  ->  dest: localhost\\SQLEXPRESS/QMS_DA")
    print(f"  output dir: {OUT_DIR}\n")

    # Order matters because of FK:
    #   DM_HangDoi  (used by Sys_Users_PhongBan)
    #   DM_PhongBan (used by Sys_Users_PhongBan)
    #   Sys_Users
    #   Sys_Users_PhongBan (FK on User_Id - logical, no constraint in our schema)
    #   Menu, Permission
    #   DM_LoaiDichVu -> DM_NhomDichVu -> DM_DichVu (FK chain)
    #   BenhNhan -> BenhNhan_BHYT (FK chain)
    #   DM_DoiTuong (independent)
    summary: dict[str, Any] = {}

    summary["DM_HangDoi"] = clone_dm_hangdoi()
    summary["DM_PhongBan+Loai"] = clone_dm_phongban()
    u, upb, _ = clone_users_menu()
    summary["Sys_Users"] = u
    summary["Sys_Users_PhongBan"] = upb
    m, p = clone_menu_permission()
    summary["Menu"] = m
    summary["Permission"] = p
    ndb, tgdv, dtut = clone_misc()
    summary["DM_NoiDungDacBiet"] = ndb
    summary["DM_ThoiGianDichVu"] = f"SKIPPED (FK -> DM_DichVu, optional)"
    summary["K_DM_DoiTuongUuTien"] = dtut
    loai, nhom, dv = clone_dichvu_catalog()
    summary["DM_LoaiDichVu"] = loai
    summary["DM_NhomDichVu"] = nhom
    summary["DM_DichVu"] = dv
    nbn, nbhyt = clone_benhnhan()
    summary["BenhNhan"] = nbn
    summary["BenhNhan_BHYT"] = nbhyt
    summary["DM_DoiTuong"] = seed_dm_doituong()

    print("\n" + "=" * 60)
    print("SUMMARY (inserted this run):")
    print("=" * 60)
    for k, v in summary.items():
        print(f"  {k:30s} = {v}")

    verify_counts()
    smoke_test_sp()
    return 0


if __name__ == "__main__":
    sys.exit(main())
